package com.mdeo.script.compiler.statements

import com.mdeo.expression.ast.statements.TypedIfStatement
import com.mdeo.expression.ast.statements.TypedStatement
import com.mdeo.script.compiler.CompilationContext
import com.mdeo.script.compiler.Scope
import com.mdeo.script.compiler.StatementCompiler
import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Compiles if statements to bytecode.
 * 
 * Handles all variations:
 * - Simple if
 * - If-else
 * - If-else if-else (multiple else-if clauses)
 * 
 * Each block (then, else-if, else) creates a new scope.
 * 
 * Generated bytecode structure for if-else if-else:
 * ```
 *   [evaluate condition]
 *   IFEQ elseIf1Label       ; if condition is false, go to first else-if
 *   [then block]
 *   GOTO endLabel
 * elseIf1Label:
 *   [evaluate else-if condition]
 *   IFEQ elseIf2Label       ; if condition is false, go to next else-if or else
 *   [else-if block]
 *   GOTO endLabel
 * ...
 * elseLabel:
 *   [else block]
 * endLabel:
 * ```
 */
class IfStatementCompiler : StatementCompiler {
    
    /**
     * Checks if this compiler can handle the given statement.
     *
     * @param statement the statement to check
     * @return true if the statement is a [TypedIfStatement], false otherwise
     */
    override fun canCompile(statement: TypedStatement): Boolean {
        return statement is TypedIfStatement
    }
    
    /**
     * Compiles an if statement to bytecode.
     *
     * Evaluates the condition and uses IFEQ to jump to the next branch if false.
     * Each branch (then, else-if, else) is compiled in its own scope.
     *
     * @param statement the if statement to compile (must be a [TypedIfStatement])
     * @param context the compilation context containing scope and expression compilation utilities
     * @param mv the method visitor for emitting bytecode
     */
    override fun compile(statement: TypedStatement, context: CompilationContext, mv: MethodVisitor) {
        val ifStmt = statement as TypedIfStatement
        
        val endLabel = Label()
        val nextBranchLabel = Label()
        
        val conditionType = context.getType(ifStmt.condition.evalType)
        context.compileExpression(ifStmt.condition, mv, conditionType)
        mv.visitJumpInsn(Opcodes.IFEQ, nextBranchLabel)
        
        compileThenBlock(ifStmt, context, mv)
        
        val hasElseIfs = ifStmt.elseIfs.isNotEmpty()
        val hasElse = ifStmt.elseBlock != null
        
        if (hasElseIfs || hasElse) {
            mv.visitJumpInsn(Opcodes.GOTO, endLabel)
        }
        
        mv.visitLabel(nextBranchLabel)
        
        if (hasElseIfs) {
            compileElseIfs(ifStmt, context, mv, endLabel)
        } else if (hasElse) {
            compileElseBlock(ifStmt, context, mv)
        }
        
        if (hasElseIfs || hasElse) {
            mv.visitLabel(endLabel)
        }
    }
    
    /**
     * Compiles the then block of an if statement.
     *
     * Creates a new scope for the block and compiles all statements within it.
     *
     * @param ifStmt the if statement containing the then block
     * @param context the compilation context
     * @param mv the method visitor for emitting bytecode
     */
    private fun compileThenBlock(
        ifStmt: TypedIfStatement,
        context: CompilationContext,
        mv: MethodVisitor
    ) {
        val thenScope = context.getStatementScope(ifStmt)
            ?: throw IllegalStateException(
                "If statement then-block scope not found in scope tree. This indicates a bug in ScopeBuilder - " +
                "all if statements should have their scopes registered during scope building phase."
            )
        
        context.enterScope(thenScope)
        
        for (stmt in ifStmt.thenBlock) {
            context.compileStatement(stmt, mv)
        }
        
        context.exitScope()
    }
    
    /**
     * Compiles all else-if clauses and the final else block if present.
     *
     * Iterates through each else-if clause, compiling the condition and body.
     * Uses IFEQ to jump to the next clause when the condition is false.
     * After each else-if body, emits GOTO to jump to the end label (unless it's
     * the last clause with no else block).
     *
     * @param ifStmt the if statement containing the else-if clauses
     * @param context the compilation context
     * @param mv the method visitor for emitting bytecode
     * @param endLabel the label marking the end of the entire if statement
     */
    private fun compileElseIfs(
        ifStmt: TypedIfStatement,
        context: CompilationContext,
        mv: MethodVisitor,
        endLabel: Label
    ) {
        for ((index, elseIf) in ifStmt.elseIfs.withIndex()) {
            val isLast = index == ifStmt.elseIfs.size - 1
            val nextLabel = Label()
            
            val elseIfConditionType = context.getType(elseIf.condition.evalType)
            context.compileExpression(elseIf.condition, mv, elseIfConditionType)
            mv.visitJumpInsn(Opcodes.IFEQ, nextLabel)
            
            val elseIfScope = context.getStatementScope(elseIf)
                ?: throw IllegalStateException(
                    "Else-if block scope could not be created. This indicates a missing parent scope."
                )
            
            context.enterScope(elseIfScope)
            
            for (stmt in elseIf.thenBlock) {
                context.compileStatement(stmt, mv)
            }
            
            context.exitScope()
            
            if (isLast && ifStmt.elseBlock == null) {
                mv.visitLabel(nextLabel)
            } else {
                mv.visitJumpInsn(Opcodes.GOTO, endLabel)
                mv.visitLabel(nextLabel)
            }
        }
        
        if (ifStmt.elseBlock != null) {
            compileElseBlock(ifStmt, context, mv)
        }
    }
    
    /**
     * Compiles the else block of an if statement.
     *
     * Creates a new scope for the block and compiles all statements within it.
     * Returns early if there is no else block.
     *
     * @param ifStmt the if statement containing the else block
     * @param context the compilation context
     * @param mv the method visitor for emitting bytecode
     */
    private fun compileElseBlock(
        ifStmt: TypedIfStatement,
        context: CompilationContext,
        mv: MethodVisitor
    ) {
        val elseBlock = ifStmt.elseBlock ?: return
        
        val elseScope = context.getStatementScope(elseBlock)
            ?: throw IllegalStateException(
                "Else block scope could not be created. This indicates a missing parent scope."
            )
        
        context.enterScope(elseScope)
        
        for (stmt in elseBlock) {
            context.compileStatement(stmt, mv)
        }
        
        context.exitScope()
    }
}
