package com.mdeo.script.compiler.statements

import com.mdeo.script.ast.statements.TypedStatement
import com.mdeo.script.ast.statements.TypedWhileStatement
import com.mdeo.script.compiler.CompilationContext
import com.mdeo.script.compiler.LoopLabels
import com.mdeo.script.compiler.Scope
import com.mdeo.script.compiler.StatementCompiler
import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Compiles while statements to bytecode.
 * 
 * Structure:
 * loopStart:
 *   [evaluate condition]
 *   IFEQ loopEnd        ; if false, exit loop
 *   [body statements]
 *   GOTO loopStart      ; repeat
 * loopEnd:
 * 
 * This compiler also registers loop labels with the compilation context
 * to support break and continue statements.
 */
class WhileStatementCompiler : StatementCompiler {
    
    /**
     * Checks if this compiler can handle the given statement.
     *
     * @param statement The typed statement to check.
     * @return True if the statement is a while statement, false otherwise.
     */
    override fun canCompile(statement: TypedStatement): Boolean {
        return statement is TypedWhileStatement
    }
    
    /**
     * Compiles a while statement to JVM bytecode.
     *
     * The generated bytecode follows this structure:
     * - loopStart: evaluate condition, jump to loopEnd if false
     * - execute body statements
     * - jump back to loopStart
     * - loopEnd: continue after loop
     *
     * Loop labels are registered with the context to support break and continue statements.
     *
     * @param statement The typed while statement to compile.
     * @param context The compilation context containing scope and type information.
     * @param mv The method visitor used to emit bytecode instructions.
     * @return Unit.
     */
    override fun compile(statement: TypedStatement, context: CompilationContext, mv: MethodVisitor) {
        val whileStmt = statement as TypedWhileStatement
        
        val loopStart = Label()
        val loopEnd = Label()
        
        val loopLabels = LoopLabels(continueLabel = loopStart, breakLabel = loopEnd)
        context.pushLoopLabels(loopLabels)
        
        mv.visitLabel(loopStart)
        
        context.compileExpression(whileStmt.condition, mv)
        
        val conditionType = context.getType(whileStmt.condition.evalType)
        emitBooleanJump(conditionType, loopEnd, mv)
        
        val whileScope = context.getStatementScope(whileStmt)
            ?: throw IllegalStateException(
                "While statement scope not found in scope tree. This indicates a bug in ScopeBuilder - " +
                "all while statements should have their scopes registered during scope building phase."
            )
        
        context.enterScope(whileScope)
        
        for (bodyStatement in whileStmt.body) {
            context.compileStatement(bodyStatement, mv)
        }
        
        context.exitScope()
        
        mv.visitJumpInsn(Opcodes.GOTO, loopStart)
        
        mv.visitLabel(loopEnd)
        
        context.popLoopLabels()
    }
    
    /**
     * Emits a conditional jump based on a boolean condition.
     *
     * Jumps to the target label if the condition is false (0).
     *
     * @param conditionType The type of the condition expression (expected to be boolean).
     * @param falseLabel The label to jump to when the condition evaluates to false.
     * @param mv The method visitor used to emit the jump instruction.
     * @return Unit.
     */
    private fun emitBooleanJump(
        conditionType: com.mdeo.script.ast.types.ReturnType,
        falseLabel: Label,
        mv: MethodVisitor
    ) {
        mv.visitJumpInsn(Opcodes.IFEQ, falseLabel)
    }
}
