/**
 * Centralized ID generator for model transformation diagram elements.
 * Provides stable, deterministic ID generation for synthetic elements based on source element IDs.
 * 
 * This class ensures that IDs are identical when generated by both the GModel factory
 * and the metadata manager, preventing ID mismatches during diagram synchronization.
 */
export class ModelTransformationIdGenerator {
    /**
     * Generates an ID for a control flow edge.
     * 
     * @param sourceId The source node ID
     * @param targetId The target node ID
     * @returns The edge ID
     */
    static controlFlowEdge(sourceId: string, targetId: string): string {
        return `${sourceId}@${targetId}`;
    }

    /**
     * Generates an ID for a match node derived from a statement.
     * 
     * @param statementId The statement ID from the source model
     * @returns The match node ID
     */
    static matchNode(statementId: string): string {
        return `${statementId}_match`;
    }

    /**
     * Generates an ID for a merge node derived from a statement.
     * 
     * @param statementId The statement ID from the source model
     * @returns The merge node ID
     */
    static mergeNode(statementId: string): string {
        return `${statementId}_merge`;
    }

    /**
     * Generates an ID for a referenced pattern instance.
     * 
     * @param matchNodeId The match node ID where the instance is referenced
     * @param instanceName The name of the referenced instance
     * @returns The referenced instance node ID
     */
    static referencedInstance(matchNodeId: string, instanceName: string): string {
        return `${matchNodeId}_ref_${instanceName}`;
    }

    /**
     * Generates an ID for a control flow edge label node.
     * 
     * @param edgeId The edge ID
     * @returns The label node ID
     */
    static controlFlowEdgeLabelNode(edgeId: string): string {
        return `${edgeId}#label-node`;
    }

    /**
     * Generates an ID for a control flow edge label.
     * 
     * @param edgeId The edge ID
     * @returns The label ID
     */
    static controlFlowEdgeLabel(edgeId: string): string {
        return `${edgeId}#label`;
    }

    /**
     * Generates an ID for a pattern link source end node.
     * 
     * @param edgeId The pattern link edge ID
     * @returns The source end node ID
     */
    static patternLinkSourceEndNode(edgeId: string): string {
        return `${edgeId}#source-node`;
    }

    /**
     * Generates an ID for a pattern link target end node.
     * 
     * @param edgeId The pattern link edge ID
     * @returns The target end node ID
     */
    static patternLinkTargetEndNode(edgeId: string): string {
        return `${edgeId}#target-node`;
    }

    /**
     * Generates an ID for a pattern link source end label.
     * 
     * @param edgeId The pattern link edge ID
     * @returns The source end label ID
     */
    static patternLinkSourceEndLabel(edgeId: string): string {
        return `${edgeId}#source-label`;
    }

    /**
     * Generates an ID for a pattern link target end label.
     * 
     * @param edgeId The pattern link edge ID
     * @returns The target end label ID
     */
    static patternLinkTargetEndLabel(edgeId: string): string {
        return `${edgeId}#target-label`;
    }

    /**
     * Generates an ID for a property label.
     * 
     * @param propertyId The property element ID
     * @returns The label ID
     */
    static propertyLabel(propertyId: string): string {
        return `${propertyId}#label`;
    }

    /**
     * Generates an ID for a where clause label.
     * 
     * @param whereClauseId The where clause element ID
     * @returns The label ID
     */
    static whereClauseLabel(whereClauseId: string): string {
        return `${whereClauseId}#label`;
    }

    /**
     * Generates an ID for a variable label.
     * 
     * @param variableId The variable element ID
     * @returns The label ID
     */
    static variableLabel(variableId: string): string {
        return `${variableId}#label`;
    }

    /**
     * Generates an ID for an instance-to-match containment edge.
     * This is used in metadata for cost calculation purposes.
     * 
     * @param instanceNodeId The instance node ID
     * @param matchNodeId The match node ID
     * @returns The containment edge ID
     */
    static instanceToMatchEdge(instanceNodeId: string, matchNodeId: string): string {
        return `${instanceNodeId}@${matchNodeId}`;
    }
}
