/**
 * Centralized ID generator for model transformation diagram elements.
 * Provides stable, deterministic ID generation for synthetic elements based on source element IDs.
 *
 * This class ensures that IDs are identical when generated by both the GModel factory
 * and the metadata manager, preventing ID mismatches during diagram synchronization.
 */
export class ModelTransformationIdGenerator {
    /**
     * Generates an ID for a control flow edge.
     * When a label is provided, it is included in the ID to make edges unique
     * even when multiple labeled edges exist between the same source and target nodes.
     *
     * @param sourceId The source node ID
     * @param targetId The target node ID
     * @param label Optional edge label (e.g. "then", "else", condition text)
     * @returns The edge ID
     */
    static controlFlowEdge(sourceId: string, targetId: string, label?: string): string {
        if (label != undefined) {
            return `${sourceId}_to_${targetId}_label_${label}`;
        }
        return `${sourceId}_to_${targetId}`;
    }

    /**
     * Generates an ID for a merge node derived from a statement.
     *
     * @param statementId The statement ID from the source model
     * @returns The merge node ID
     */
    static mergeNode(statementId: string): string {
        return `${statementId}_merge`;
    }

    /**
     * Generates an ID for an instance-to-match containment edge.
     * This is used in metadata for cost calculation purposes.
     *
     * @param instanceNodeId The instance node ID
     * @param matchNodeId The match node ID
     * @returns The containment edge ID
     */
    static instanceToMatchEdge(instanceNodeId: string, matchNodeId: string): string {
        return `${instanceNodeId}_in_${matchNodeId}`;
    }
}
