/**
 * Centralized ID generator for model transformation diagram elements.
 * Provides stable, deterministic ID generation for synthetic elements based on source element IDs.
 *
 * This class ensures that IDs are identical when generated by both the GModel factory
 * and the metadata manager, preventing ID mismatches during diagram synchronization.
 */
export class ModelTransformationIdGenerator {
    /**
     * Generates an ID for a control flow edge.
     *
     * @param sourceId The source node ID
     * @param targetId The target node ID
     * @returns The edge ID
     */
    static controlFlowEdge(sourceId: string, targetId: string): string {
        return `${sourceId}@${targetId}`;
    }

    /**
     * Generates an ID for a merge node derived from a statement.
     *
     * @param statementId The statement ID from the source model
     * @returns The merge node ID
     */
    static mergeNode(statementId: string): string {
        return `${statementId}_merge`;
    }

    /**
     * Generates an ID for an instance-to-match containment edge.
     * This is used in metadata for cost calculation purposes.
     *
     * @param instanceNodeId The instance node ID
     * @param matchNodeId The match node ID
     * @returns The containment edge ID
     */
    static instanceToMatchEdge(instanceNodeId: string, matchNodeId: string): string {
        return `${instanceNodeId}@${matchNodeId}`;
    }
}
