import type { AstReflection } from "@mdeo/language-common";
import type { ModelIdRegistry } from "@mdeo/language-shared";
import {
    MatchStatement,
    IfMatchStatement,
    WhileMatchStatement,
    UntilMatchStatement,
    ForMatchStatement,
    IfExpressionStatement,
    WhileExpressionStatement,
    StopStatement
} from "../../grammar/modelTransformationTypes.js";
import type {
    ModelTransformationType,
    BaseTransformationStatementType,
    MatchStatementType,
    IfMatchStatementType,
    WhileMatchStatementType,
    UntilMatchStatementType,
    ForMatchStatementType,
    IfExpressionStatementType,
    WhileExpressionStatementType,
    StopStatementType,
    PatternType,
    ElseIfBranchType
} from "../../grammar/modelTransformationTypes.js";
import { ModelTransformationIdGenerator } from "./modelTransformationIdGenerator.js";

/**
 * A start node marking the single entry point of the transformation.
 */
export interface ControlFlowStartNode {
    /**
     * Discriminant — always "start".
     */
    readonly kind: "start";
    /**
     * Unique node ID.
     */
    readonly id: string;
}

/**
 * An end node marking a termination point of the transformation.
 */
export interface ControlFlowEndNode {
    /**
     * Discriminant — always "end".
     */
    readonly kind: "end";
    /**
     * Unique node ID.
     */
    readonly id: string;
    /**
     * The kind of termination:
     * - "stop" — normal completion or explicit stop statement.
     * - "kill" — hard termination via kill statement.
     */
    readonly endKind: "stop" | "kill";
}

/**
 * A match node corresponding to a pattern-match statement in the transformation.
 * The pattern AST node is included so consumers can render its content independently.
 */
export interface ControlFlowMatchNode {
    /**
     * Discriminant — always "match".
     */
    readonly kind: "match";
    /**
     * Unique node ID (equals the pattern registry ID when a pattern is present).
     */
    readonly id: string;
    /**
     * The name part of the id
     */
    readonly matchName: string;
    /**
     * true for for-match statements that iterate over every result;
     * false for all other match variants.
     */
    readonly multiple: boolean;
    /**
     * The pattern AST node, or undefined when the statement carries no pattern.
     */
    readonly pattern: PatternType | undefined;
}

/**
 * A split node corresponding to an expression-based branching statement
 * (if-expression or while-expression).
 */
export interface ControlFlowSplitNode {
    /**
     * Discriminant — always "split".
     */
    readonly kind: "split";
    /**
     * Unique node ID.
     */
    readonly id: string;
    /**
     * The condition expression source text, used as the display label on the node.
     */
    readonly conditionText: string;
}

/**
 * A merge node where two or more branches of the control flow rejoin.
 */
export interface ControlFlowMergeNode {
    /**
     * Discriminant — always "merge".
     */
    readonly kind: "merge";
    /**
     * Unique node ID.
     */
    readonly id: string;
}

/**
 * Discriminated union of all supported control-flow node kinds.
 */
export type ControlFlowNode =
    | ControlFlowStartNode
    | ControlFlowEndNode
    | ControlFlowMatchNode
    | ControlFlowSplitNode
    | ControlFlowMergeNode;

/**
 * A directed edge in the control-flow graph.
 */
export interface ControlFlowEdge {
    /**
     * Unique edge ID generated by ModelTransformationIdGenerator.controlFlowEdge.
     */
    readonly id: string;
    /**
     * ID of the source node.
     */
    readonly sourceId: string;
    /**
     * ID of the target node.
     */
    readonly targetId: string;
    /**
     * Optional label text displayed on the edge.
     *
     * For match-based branches: "then", "else", "match", "no match", "each".
     * For expression-based branches: the condition expression text or "else".
     */
    readonly label?: string;
    /**
     * When set, the GModel label element on this edge should use this ID instead of
     * the default "${edgeId}#label".  Setting this makes the label editable in the
     * diagram editor and ties the edit to the corresponding AST node.
     *
     * This field is relevant only for the GModel factory; the metadata manager
     * should ignore it.
     */
    readonly labelElementId?: string;
}

/**
 * The control-flow graph extracted from a ModelTransformationType.
 *
 * The graph captures only the outer activity-diagram structure:
 * - start / end nodes
 * - match nodes (with the raw pattern AST node for consumer-side rendering)
 * - split / merge nodes for expression-based branching
 * - directed edges with optional labels
 *
 * Pattern content (instances, links, where-clauses, variables, etc.) is
 * intentionally excluded and left to the consuming class.
 */
export interface ControlFlowGraph {
    /**
     * The ID of the unique start node.
     */
    readonly startNodeId: string;
    /**
     * All nodes in graph traversal order.
     */
    readonly nodes: readonly ControlFlowNode[];
    /**
     * All control-flow edges.
     */
    readonly edges: readonly ControlFlowEdge[];
}

/**
 * Intermediate result returned by every process* traversal helper.
 */
interface TraversalResult {
    /**
     * The ID of the last node produced, or undefined when the sub-graph
     * terminates unconditionally (e.g. via a stop/kill statement).
     */
    lastNodeId: string | undefined;
    /**
     * When set, the outgoing edge from lastNodeId to the next node should carry
     * this label.  Used by while-expression to propagate "else".
     */
    exitLabel?: string;
    /**
     * Optional label element id for the outgoing edge label. When set, the
     * edge should use this id for the label element (factory-only).
     */
    exitLabelElementId?: string;
}

/**
 * Converts a ModelTransformationType AST into a ControlFlowGraph meta-format
 * that captures the outer activity-diagram control-flow structure.
 *
 * This class is the single source of truth for:
 * - all node and edge IDs in the control-flow graph
 * - the structural shape of the graph (branches, loops, merge points)
 * - edge labels
 *
 * Both the GModel factory and the metadata manager must instantiate this
 * converter and consume the returned ControlFlowGraph rather than duplicating
 * the traversal logic themselves.
 */
export class ModelTransformationControlFlowConverter {
    private readonly model: ModelTransformationType;
    private readonly idRegistry: ModelIdRegistry;
    private readonly reflection: AstReflection;

    private nodes: ControlFlowNode[] = [];
    private edges: ControlFlowEdge[] = [];

    /**
     * @param model The transformation AST root to convert.
     * @param idRegistry Registry that maps AST nodes to stable diagram IDs.
     * @param reflection AST reflection service used for isInstance type checks.
     */
    constructor(model: ModelTransformationType, idRegistry: ModelIdRegistry, reflection: AstReflection) {
        this.model = model;
        this.idRegistry = idRegistry;
        this.reflection = reflection;
    }

    /**
     * Performs the conversion and returns the complete control-flow graph.
     *
     * Calling this method multiple times re-traverses the model and returns a
     * fresh graph each time.
     *
     * @returns The ControlFlowGraph for the transformation.
     */
    convert(): ControlFlowGraph {
        this.nodes = [];
        this.edges = [];

        const startNodeId = "start";
        this.pushNode({ kind: "start", id: startNodeId });

        const statements = this.model.statements ?? [];
        const result = this.processStatements(statements, startNodeId, undefined);

        if (result.lastNodeId != undefined) {
            const endNodeId = "implicit_end";
            this.pushNode({ kind: "end", id: endNodeId, endKind: "stop" });
            this.pushEdge(result.lastNodeId, endNodeId, result.exitLabel);
        }

        return {
            startNodeId,
            nodes: [...this.nodes],
            edges: [...this.edges]
        };
    }

    /**
     * Appends a node to the internal accumulator.
     *
     * @param node The node to append.
     */
    private pushNode(node: ControlFlowNode): void {
        this.nodes.push(node);
    }

    /**
     * Creates an edge and appends it to the internal accumulator.
     * When a label is provided it is included in the edge ID so that two labeled
     * edges with different labels between the same source and target nodes remain
     * distinct (e.g. "then" and "else" edges from an if-match pattern node).
     *
     * @param sourceId The source node ID.
     * @param targetId The target node ID.
     * @param label Optional label text for the edge.
     * @param labelElementId Optional GModel label element ID (factory-only).
     */
    private pushEdge(sourceId: string, targetId: string, label?: string, labelElementId?: string): void {
        const id = ModelTransformationIdGenerator.controlFlowEdge(sourceId, targetId, label);
        let edge: ControlFlowEdge;
        if (label != undefined && labelElementId != undefined) {
            edge = { id, sourceId, targetId, label, labelElementId };
        } else if (label != undefined) {
            edge = { id, sourceId, targetId, label };
        } else {
            edge = { id, sourceId, targetId };
        }
        this.edges.push(edge);
    }

    /**
     * Appends a ControlFlowMatchNode to the accumulator.
     *
     * @param id The node ID.
     * @param matchName The display name shown in the node header.
     * @param multiple true when this iterates over all matches (for-match).
     * @param pattern The optional pattern AST node.
     */
    private pushMatchNode(id: string, matchName: string, multiple: boolean, pattern: PatternType | undefined): void {
        this.pushNode({ kind: "match", id, matchName, multiple, pattern });
    }

    /**
     * Processes a list of statements in sequence, threading the predecessor
     * node ID and any pending exit label through each successive statement.
     *
     * @param statements The statements to process.
     * @param previousNodeId The direct predecessor node ID.
     * @param incomingLabel Optional label for the edge into the first statement.
     * @returns The traversal result after the last statement.
     */
    private processStatements(
        statements: BaseTransformationStatementType[],
        previousNodeId: string,
        incomingLabel: string | undefined
    ): TraversalResult {
        let currentNodeId: string | undefined = previousNodeId;
        let pendingLabel: string | undefined = incomingLabel;
        let pendingLabelElementId: string | undefined = undefined;

        for (const stmt of statements) {
            if (stmt == undefined || currentNodeId == undefined) {
                continue;
            }
            const result = this.processStatement(stmt, currentNodeId, pendingLabel);
            currentNodeId = result.lastNodeId;
            pendingLabel = result.exitLabel;
            pendingLabelElementId = result.exitLabelElementId;
        }

        return { lastNodeId: currentNodeId, exitLabel: pendingLabel, exitLabelElementId: pendingLabelElementId };
    }

    /**
     * Dispatches a single statement to the appropriate typed handler.
     *
     * @param stmt The statement to dispatch.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID for the incoming edge (factory-only).
     * @returns The traversal result.
     */
    private processStatement(
        stmt: BaseTransformationStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        if (this.reflection.isInstance(stmt, MatchStatement)) {
            return this.processMatchStatement(
                stmt as MatchStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, IfMatchStatement)) {
            return this.processIfMatchStatement(
                stmt as IfMatchStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, WhileMatchStatement)) {
            return this.processWhileMatchStatement(
                stmt as WhileMatchStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, UntilMatchStatement)) {
            return this.processUntilMatchStatement(
                stmt as UntilMatchStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, ForMatchStatement)) {
            return this.processForMatchStatement(
                stmt as ForMatchStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, IfExpressionStatement)) {
            return this.processIfExpressionStatement(
                stmt as IfExpressionStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, WhileExpressionStatement)) {
            return this.processWhileExpressionStatement(
                stmt as WhileExpressionStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        if (this.reflection.isInstance(stmt, StopStatement)) {
            return this.processStopStatement(
                stmt as StopStatementType,
                previousNodeId,
                incomingLabel,
                incomingLabelElementId
            );
        }
        return { lastNodeId: previousNodeId };
    }

    /**
     * Processes a simple match statement.
     *
     * @param stmt The match statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result with the match node as the last node.
     */
    private processMatchStatement(
        stmt: MatchStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const nodeId = this.idRegistry.getId(stmt);
        const matchName = this.idRegistry.getName(stmt) ?? nodeId;
        this.pushMatchNode(nodeId, matchName, false, stmt.pattern);
        this.pushEdge(previousNodeId, nodeId, incomingLabel, incomingLabelElementId);
        return { lastNodeId: nodeId };
    }

    /**
     * Processes an if-match statement.
     * Emits a match node, then/else branches, and a merge node for non-terminating branches.
     *
     * @param stmt The if-match statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result ending at the merge node, or undefined if all branches terminate.
     */
    private processIfMatchStatement(
        stmt: IfMatchStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const stmtId = this.idRegistry.getId(stmt);
        const pattern = stmt.ifBlock?.pattern;
        const matchNodeId = pattern != undefined ? this.idRegistry.getId(pattern) : `${stmtId}_no-pattern`;
        const matchName = (pattern != undefined ? this.idRegistry.getName(pattern) : undefined) ?? stmtId;

        this.pushMatchNode(matchNodeId, matchName, false, pattern);
        this.pushEdge(previousNodeId, matchNodeId, incomingLabel, incomingLabelElementId);

        return this.processIfMatchBranches(stmt, stmtId, matchNodeId);
    }

    /**
     * Processes the then/else branches of an if-match statement.
     *
     * Both the "then" and "else" edges are always emitted — even when the else block
     * does not exist in the source — so that the diagram always offers an insertion
     * point on the else path.
     *
     * @param stmt The if-match statement.
     * @param stmtId The statement registry ID, used to derive the merge node ID.
     * @param matchNodeId The match node acting as the branch origin.
     * @returns Traversal result ending at the merge node, or undefined if all branches terminate.
     */
    private processIfMatchBranches(stmt: IfMatchStatementType, stmtId: string, matchNodeId: string): TraversalResult {
        const thenStatements = stmt.ifBlock?.thenBlock?.statements ?? [];
        const elseStatements = stmt.elseBlock?.statements ?? [];

        const thenResult = this.processBranch(thenStatements, matchNodeId, "then");
        // Always process the else path so the else edge is always present in the diagram,
        // even when no else block exists in the code.
        const elseResult = this.processBranch(elseStatements, matchNodeId, "else");

        if (thenResult.lastNodeId != undefined || elseResult.lastNodeId != undefined) {
            const mergeNodeId = ModelTransformationIdGenerator.mergeNode(stmtId);
            this.pushNode({ kind: "merge", id: mergeNodeId });

            if (thenResult.lastNodeId != undefined) {
                this.pushEdge(thenResult.lastNodeId, mergeNodeId, thenResult.exitLabel, thenResult.exitLabelElementId);
            }
            if (elseResult.lastNodeId != undefined) {
                this.pushEdge(elseResult.lastNodeId, mergeNodeId, elseResult.exitLabel, elseResult.exitLabelElementId);
            }

            return { lastNodeId: mergeNodeId };
        }

        return { lastNodeId: undefined };
    }

    /**
     * Processes a while-match statement.
     * Creates a match node with a loop-back edge from the do-block.
     *
     * @param stmt The while-match statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result with the match node as the exit point.
     */
    private processWhileMatchStatement(
        stmt: WhileMatchStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const nodeId = this.idRegistry.getId(stmt);
        const matchNodeId = stmt.pattern != undefined ? this.idRegistry.getId(stmt.pattern) : `${nodeId}_no-pattern`;
        const matchName = (stmt.pattern != undefined ? this.idRegistry.getName(stmt.pattern) : undefined) ?? nodeId;

        this.pushMatchNode(matchNodeId, matchName, false, stmt.pattern);
        this.pushEdge(previousNodeId, matchNodeId, incomingLabel, incomingLabelElementId);

        const doStatements = stmt.doBlock?.statements ?? [];
        if (doStatements.length > 0) {
            const doResult = this.processBranch(doStatements, matchNodeId, "match");
            if (doResult.lastNodeId != undefined) {
                this.pushEdge(doResult.lastNodeId, matchNodeId);
            }
        }

        return { lastNodeId: matchNodeId };
    }

    /**
     * Processes an until-match statement.
     * Executes the do-block until the pattern matches, looping back to the match node.
     *
     * @param stmt The until-match statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result with the match node as the exit point.
     */
    private processUntilMatchStatement(
        stmt: UntilMatchStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const nodeId = this.idRegistry.getId(stmt);
        const matchNodeId = stmt.pattern != undefined ? this.idRegistry.getId(stmt.pattern) : `${nodeId}_no-pattern`;
        const matchName = (stmt.pattern != undefined ? this.idRegistry.getName(stmt.pattern) : undefined) ?? nodeId;

        this.pushMatchNode(matchNodeId, matchName, false, stmt.pattern);
        this.pushEdge(previousNodeId, matchNodeId, incomingLabel, incomingLabelElementId);

        const doStatements = stmt.doBlock?.statements ?? [];
        if (doStatements.length > 0) {
            const doResult = this.processBranch(doStatements, matchNodeId, "no match");
            if (doResult.lastNodeId != undefined) {
                this.pushEdge(doResult.lastNodeId, matchNodeId);
            }
        }

        return { lastNodeId: matchNodeId };
    }

    /**
     * Processes a for-match statement.
     * Iterates over all matches of the pattern, looping back on each iteration.
     * When the do-block is empty, a self-loop edge labelled "each" is emitted so
     * that insertion points are still available in the diagram.
     *
     * @param stmt The for-match statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result with the match node as the exit point.
     */
    private processForMatchStatement(
        stmt: ForMatchStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const nodeId = this.idRegistry.getId(stmt);
        const matchNodeId = stmt.pattern != undefined ? this.idRegistry.getId(stmt.pattern) : `${nodeId}_no-pattern`;
        const matchName = (stmt.pattern != undefined ? this.idRegistry.getName(stmt.pattern) : undefined) ?? nodeId;

        this.pushMatchNode(matchNodeId, matchName, true, stmt.pattern);
        this.pushEdge(previousNodeId, matchNodeId, incomingLabel, incomingLabelElementId);

        const doStatements = stmt.doBlock?.statements ?? [];
        if (doStatements.length > 0) {
            const doResult = this.processBranch(doStatements, matchNodeId, "each");
            if (doResult.lastNodeId != undefined) {
                this.pushEdge(doResult.lastNodeId, matchNodeId);
            }
        } else {
            // Empty do-block: emit a self-loop so the diagram still shows an "each"
            // edge and users can insert statements there via the context action.
            this.pushEdge(matchNodeId, matchNodeId, "each");
        }

        return { lastNodeId: matchNodeId };
    }

    /**
     * Processes an if-expression statement.
     * Emits a split node, then/else-if/else branches, and a merge node.
     *
     * @param stmt The if-expression statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result ending at the merge node, or undefined if all branches terminate.
     */
    private processIfExpressionStatement(
        stmt: IfExpressionStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const stmtId = this.idRegistry.getId(stmt);
        const splitId = `${stmtId}_split`;
        const conditionText = stmt.condition?.$cstNode?.text ?? "?";

        this.pushNode({ kind: "split", id: splitId, conditionText });
        this.pushEdge(previousNodeId, splitId, incomingLabel, incomingLabelElementId);

        return this.processIfExpressionBranches(stmt, stmtId, splitId, conditionText);
    }

    /**
     * Processes the then/else-if/else branches of an if-expression statement.
     *
     * The else path is always processed (even when no else block exists in the source)
     * so that the diagram always shows an "else" edge. Deduplication of merge-node
     * connections is keyed on `sourceId + label` rather than `sourceId` alone, which
     * allows separate labeled edges (e.g. the condition-text edge and the "else" edge)
     * from the same split node to both be retained.
     *
     * @param stmt The if-expression statement.
     * @param stmtId The statement registry ID, used to derive merge and else-if split IDs.
     * @param splitId The split node acting as the branch origin.
     * @param conditionText The condition text used as the then-branch edge label.
     * @returns Traversal result ending at the merge node, or undefined if all branches terminate.
     */
    private processIfExpressionBranches(
        stmt: IfExpressionStatementType,
        stmtId: string,
        splitId: string,
        conditionText: string
    ): TraversalResult {
        const branchResults: TraversalResult[] = [];

        const thenStatements = stmt.thenBlock?.statements ?? [];
        let thenResult: TraversalResult;
        if (thenStatements.length === 0) {
            thenResult = { lastNodeId: splitId, exitLabel: conditionText, exitLabelElementId: stmtId };
        } else {
            thenResult = this.processBranch(thenStatements, splitId, conditionText, stmtId);
        }
        branchResults.push(thenResult);

        let lastElseIfSplitId = splitId;
        const elseIfBranches = stmt.elseIfBranches ?? [];
        for (let i = 0; i < elseIfBranches.length; i++) {
            const elseIfBranch = elseIfBranches[i] as ElseIfBranchType;
            const elseIfSplitId = `${stmtId}_elseif_${i}_split`;
            const elseIfConditionText = elseIfBranch.condition?.$cstNode?.text ?? "?";

            this.pushNode({ kind: "split", id: elseIfSplitId, conditionText: elseIfConditionText });
            this.pushEdge(lastElseIfSplitId, elseIfSplitId, "else");

            const elseIfStatements = elseIfBranch.block?.statements ?? [];
            const elseIfBranchLabelId = this.idRegistry.hasId(elseIfBranch)
                ? this.idRegistry.getId(elseIfBranch)
                : undefined;
            let elseIfResult: TraversalResult;
            if (elseIfStatements.length === 0) {
                elseIfResult = {
                    lastNodeId: elseIfSplitId,
                    exitLabel: elseIfConditionText,
                    exitLabelElementId: elseIfBranchLabelId
                };
            } else {
                elseIfResult = this.processBranch(
                    elseIfStatements,
                    elseIfSplitId,
                    elseIfConditionText,
                    elseIfBranchLabelId
                );
            }
            branchResults.push(elseIfResult);
            lastElseIfSplitId = elseIfSplitId;
        }

        // Always process the else path (using empty statements when no else block exists)
        // so that the "else" edge is always present in the diagram.
        const elseStatements = stmt.elseBlock?.statements ?? [];
        const elseResult = this.processBranch(elseStatements, lastElseIfSplitId, "else");
        branchResults.push(elseResult);

        const nonTerminating = branchResults.filter((r) => r.lastNodeId != undefined);
        if (nonTerminating.length > 0) {
            const mergeNodeId = ModelTransformationIdGenerator.mergeNode(stmtId);
            this.pushNode({ kind: "merge", id: mergeNodeId });

            // Deduplicate by (sourceId + label) so that two differently-labelled edges
            // from the same source node (e.g. the condition-text edge and the "else" edge
            // when both branches are empty) are both preserved.
            const connectedToMerge = new Set<string>();
            for (const result of nonTerminating) {
                const sourceId = result.lastNodeId!;
                const label = result.exitLabel;
                const key = `${sourceId}:${label ?? ""}`;
                if (connectedToMerge.has(key)) {
                    continue;
                }
                connectedToMerge.add(key);

                if (label != undefined) {
                    this.pushEdge(sourceId, mergeNodeId, label, result.exitLabelElementId);
                } else {
                    this.pushEdge(sourceId, mergeNodeId);
                }
            }

            return { lastNodeId: mergeNodeId };
        }

        return { lastNodeId: undefined };
    }

    /**
     * Processes a while-expression statement.
     * Emits a split node and connects the body back in a loop.
     *
     * @param stmt The while-expression statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result with the split node as the exit point and exitLabel set to "else".
     */
    private processWhileExpressionStatement(
        stmt: WhileExpressionStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const stmtId = this.idRegistry.getId(stmt);
        const splitId = `${stmtId}_split`;
        const conditionText = stmt.condition?.$cstNode?.text ?? "?";

        this.pushNode({ kind: "split", id: splitId, conditionText });
        this.pushEdge(previousNodeId, splitId, incomingLabel, incomingLabelElementId);

        const bodyStatements = stmt.block?.statements ?? [];
        if (bodyStatements.length > 0) {
            const bodyResult = this.processBranch(bodyStatements, splitId, conditionText, stmtId);
            if (bodyResult.lastNodeId != undefined) {
                this.pushEdge(bodyResult.lastNodeId, splitId);
            }
        }

        return { lastNodeId: splitId, exitLabel: "else" };
    }

    /**
     * Processes a stop or kill statement.
     *
     * @param stmt The stop/kill statement.
     * @param previousNodeId The predecessor node ID.
     * @param incomingLabel Optional label for the incoming edge.
     * @param incomingLabelElementId Optional GModel label element ID (factory-only).
     * @returns Traversal result with lastNodeId undefined (sub-graph terminates).
     */
    private processStopStatement(
        stmt: StopStatementType,
        previousNodeId: string,
        incomingLabel: string | undefined,
        incomingLabelElementId?: string
    ): TraversalResult {
        const nodeId = this.idRegistry.getId(stmt);
        const endKind: "stop" | "kill" = stmt.keyword === "kill" ? "kill" : "stop";
        this.pushNode({ kind: "end", id: nodeId, endKind });
        this.pushEdge(previousNodeId, nodeId, incomingLabel, incomingLabelElementId);
        return { lastNodeId: undefined };
    }

    /**
     * Processes a linear sequence of statements forming one branch of a conditional
     * or looping construct.
     *
     * The branchLabel is placed on the edge from sourceNodeId to the first
     * statement entry node.  When statements is empty no edge is emitted,
     * sourceNodeId is returned unchanged, and branchLabel is propagated as
     * exitLabel so that callers can still attach the label to the outgoing edge
     * from the branch origin (e.g. to a merge node).
     *
     * @param statements The branch body statements.
     * @param sourceNodeId The node from which the branch originates.
     * @param branchLabel The label placed on the edge into the first statement.
     * @param branchLabelElementId Optional GModel label element ID for the entering edge (factory-only).
     * @returns The traversal result for the complete branch.
     */
    private processBranch(
        statements: BaseTransformationStatementType[],
        sourceNodeId: string,
        branchLabel: string,
        branchLabelElementId?: string
    ): TraversalResult {
        if (statements.length === 0) {
            return { lastNodeId: sourceNodeId, exitLabel: branchLabel, exitLabelElementId: branchLabelElementId };
        }

        const firstStmt = statements[0]!;
        const firstResult = this.processStatement(firstStmt, sourceNodeId, branchLabel, branchLabelElementId);

        let currentNodeId = firstResult.lastNodeId;
        let pendingLabel = firstResult.exitLabel;
        let pendingLabelElementId = firstResult.exitLabelElementId;
        for (let i = 1; i < statements.length; i++) {
            const stmt = statements[i];
            if (stmt == undefined || currentNodeId == undefined) {
                continue;
            }
            const result = this.processStatement(stmt, currentNodeId, pendingLabel);
            currentNodeId = result.lastNodeId;
            pendingLabel = result.exitLabel;
            pendingLabelElementId = result.exitLabelElementId;
        }

        return { lastNodeId: currentNodeId, exitLabel: pendingLabel, exitLabelElementId: pendingLabelElementId };
    }
}
