package com.mdeo.script.runtime.model

/**
 * Interface for accessing properties of model instances at runtime.
 *
 * This interface provides the backing storage for model instances,
 * allowing generated instance classes to access property values
 * without knowing the underlying data representation.
 *
 * Implementations of this interface translate between the internal
 * model representation (e.g., ModelData) and the JVM types expected
 * by the generated bytecode.
 *
 * For primitive properties, the return value is the primitive value
 * (boxed if necessary). For enum properties, the return value is the
 * appropriate enum singleton object. For associations, the return value
 * is either a single ModelInstance or a List<ModelInstance>.
 */
interface ModelInstanceBacking {
    /**
     * Gets the value of a property by name.
     *
     * @param name The property name.
     * @return The property value, which may be:
     *         - A primitive value (String, Int, Long, Float, Double, Boolean)
     *         - An enum value singleton
     *         - A ModelInstance (for single-valued associations)
     *         - A List<ModelInstance> (for multi-valued associations)
     *         - null if the property is not set
     */
    fun getProperty(name: String): Any?

    /**
     * Gets the instance name for display purposes.
     *
     * @return The instance name/identifier.
     */
    fun getInstanceName(): String

    /**
     * Gets the class name of this instance.
     *
     * @return The class name from the metamodel.
     */
    fun getClassName(): String
}
