package com.mdeo.script.runtime

import com.mdeo.script.compiler.CompiledProgram

/**
 * Custom ClassLoader for loading compiled script classes.
 *
 * This ClassLoader loads the bytecode generated by the ScriptCompiler
 * and makes the classes available for execution. It also handles loading
 * the generated functional interfaces used by lambdas.
 *
 * @param program The compiled program containing the bytecode to load.
 * @param parent The parent ClassLoader.
 */
class ScriptClassLoader(
    private val program: CompiledProgram,
    parent: ClassLoader = ScriptClassLoader::class.java.classLoader
) : ClassLoader(parent) {
    
    /**
     * Cache of loaded classes by file URI.
     */
    private val loadedClasses = mutableMapOf<String, Class<*>>()
    
    /**
     * Cache of loaded interface classes by interface name.
     */
    private val loadedInterfaces = mutableMapOf<String, Class<*>>()

    /**
     * Cache of loaded model classes by class name.
     */
    private val loadedModelClasses = mutableMapOf<String, Class<*>>()
    
    /**
     * Loads the class for a given file URI.
     * 
     * @param fileUri The file URI to load the class for.
     * @return The loaded Class.
     * @throws ClassNotFoundException if no class is compiled for the given file URI.
     */
    fun loadClassForFile(fileUri: String): Class<*> {
        return loadedClasses.getOrPut(fileUri) {
            val compiledClass = program.classes[fileUri]
                ?: throw ClassNotFoundException("No compiled class for file: $fileUri")
            
            defineClass(
                compiledClass.className.replace("/", "."),
                compiledClass.bytecode,
                0,
                compiledClass.bytecode.size
            )
        }
    }
    
    override fun findClass(name: String): Class<*> {
        val internalName = name.replace(".", "/")
        
        // Check generated interfaces (lambdas)
        val interfaceBytecode = program.generatedInterfaces[internalName]
        if (interfaceBytecode != null) {
            return loadedInterfaces.getOrPut(internalName) {
                defineClass(name, interfaceBytecode, 0, interfaceBytecode.size)
            }
        }

        // Check generated model classes (ModelInstance subclasses, enums)
        val modelClassBytecode = program.generatedModelClasses[internalName]
        if (modelClassBytecode != null) {
            return loadedModelClasses.getOrPut(internalName) {
                defineClass(name, modelClassBytecode, 0, modelClassBytecode.size)
            }
        }
        
        // Check compiled script classes
        val compiledClass = program.classes.values.find { it.className == internalName }
            ?: throw ClassNotFoundException(name)
        
        return defineClass(name, compiledClass.bytecode, 0, compiledClass.bytecode.size)
    }
}
