package com.mdeo.script.compiler.model

import com.mdeo.expression.ast.types.ClassData
import com.mdeo.expression.ast.types.MetamodelData
import com.mdeo.expression.ast.types.PropertyData
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes

/**
 * Generates JVM bytecode for metamodel class instances.
 *
 * For each class in the metamodel, a JVM class is generated that:
 * - Extends ModelInstance
 * - Has a constructor taking ModelInstanceBacking
 * - Has getter methods for each property that delegate to the backing
 *
 * Example: For `class Foo { name: String, count: Int }`:
 * ```
 * class FooInstance extends ModelInstance {
 *     FooInstance(ModelInstanceBacking backing) { super(backing); }
 *     String getName() { return (String) backing.getProperty("name"); }
 *     int getCount() { return (Integer) backing.getProperty("count"); }
 * }
 * ```
 */
object ScriptClassBytecodeGenerator {

    /**
     * Internal package for generated instance classes.
     */
    private const val INSTANCE_PACKAGE = "com/mdeo/script/generated/model/instance"

    /**
     * Internal package for generated class container classes.
     */
    private const val CONTAINER_PACKAGE = "com/mdeo/script/generated/model/classcontainer"

    /**
     * Internal name of the ModelInstance base class.
     */
    private const val MODEL_INSTANCE_CLASS = "com/mdeo/script/runtime/model/ModelInstance"

    /**
     * Internal name of the ModelInstanceBacking interface.
     */
    private const val MODEL_INSTANCE_BACKING = "com/mdeo/script/runtime/model/ModelInstanceBacking"

    /**
     * Internal name of the ExecutionContext class.
     */
    private const val EXECUTION_CONTEXT_CLASS = "com/mdeo/script/runtime/ExecutionContext"

    /**
     * Internal name of the ScriptModel class.
     */
    private const val SCRIPT_MODEL_CLASS = "com/mdeo/script/runtime/model/ScriptModel"

    /**
     * Result of class bytecode generation.
     *
     * @param classBytecodes Map of class internal name to bytecode
     * @param containerBytecodes Map of class container internal name to bytecode
     */
    data class ClassBytecodeResult(
        val classBytecodes: Map<String, ByteArray>,
        val containerBytecodes: Map<String, ByteArray> = emptyMap()
    )

    /**
     * Generates bytecode for all classes in the metamodel.
     *
     * Also generates class container classes that expose an `all()` method
     * returning all instances of each class via the execution context.
     *
     * @param metamodelData The metamodel containing class definitions.
     * @param metamodelPath The absolute path of the metamodel (used for namespacing).
     * @return ClassBytecodeResult containing generated bytecodes.
     */
    fun generateClassBytecodes(
        metamodelData: MetamodelData,
        metamodelPath: String
    ): ClassBytecodeResult {
        val classBytecodes = mutableMapOf<String, ByteArray>()
        val containerBytecodes = mutableMapOf<String, ByteArray>()

        val classMap = metamodelData.classes.associateBy { it.name }

        for (classData in metamodelData.classes) {
            val (className, bytecode) = generateInstanceClass(
                classData,
                metamodelPath,
                classMap,
                metamodelData
            )
            classBytecodes[className] = bytecode

            val (containerClassName, containerBytecode) = generateClassContainerClass(
                classData.name,
                metamodelPath
            )
            containerBytecodes[containerClassName] = containerBytecode
        }

        return ClassBytecodeResult(classBytecodes, containerBytecodes)
    }

    /**
     * Generates a class container class for a metamodel class.
     *
     * The container class:
     * - Has a private constructor (instantiated only via static initializer)
     * - Has a public static final INSTANCE field
     * - Has an `all()` method that retrieves all instances via ExecutionContext
     *
     * @param className The metamodel class name.
     * @param metamodelPath The metamodel path for namespacing.
     * @return Pair of (JVM internal class name, bytecode).
     */
    fun generateClassContainerClass(
        className: String,
        metamodelPath: String
    ): Pair<String, ByteArray> {
        val containerClassName = getClassContainerClassName(className, metamodelPath)
        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)

        cw.visit(
            Opcodes.V11,
            Opcodes.ACC_PUBLIC or Opcodes.ACC_FINAL,
            containerClassName,
            null,
            "java/lang/Object",
            null
        )

        cw.visitField(
            Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC or Opcodes.ACC_FINAL,
            "INSTANCE",
            "L$containerClassName;",
            null,
            null
        )?.visitEnd()

        val clinit = cw.visitMethod(Opcodes.ACC_STATIC, "<clinit>", "()V", null, null)
        clinit.visitCode()
        clinit.visitTypeInsn(Opcodes.NEW, containerClassName)
        clinit.visitInsn(Opcodes.DUP)
        clinit.visitMethodInsn(Opcodes.INVOKESPECIAL, containerClassName, "<init>", "()V", false)
        clinit.visitFieldInsn(Opcodes.PUTSTATIC, containerClassName, "INSTANCE", "L$containerClassName;")
        clinit.visitInsn(Opcodes.RETURN)
        clinit.visitMaxs(0, 0)
        clinit.visitEnd()

        val init = cw.visitMethod(Opcodes.ACC_PRIVATE, "<init>", "()V", null, null)
        init.visitCode()
        init.visitVarInsn(Opcodes.ALOAD, 0)
        init.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false)
        init.visitInsn(Opcodes.RETURN)
        init.visitMaxs(0, 0)
        init.visitEnd()

        val allMv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "all",
            "()Ljava/util/List;",
            null,
            null
        )
        allMv.visitCode()
        allMv.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            EXECUTION_CONTEXT_CLASS,
            "requireModel",
            "()L$SCRIPT_MODEL_CLASS;",
            false
        )
        allMv.visitLdcInsn(className)
        allMv.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            SCRIPT_MODEL_CLASS,
            "getAllInstances",
            "(Ljava/lang/String;)Ljava/util/List;",
            false
        )
        allMv.visitInsn(Opcodes.ARETURN)
        allMv.visitMaxs(0, 0)
        allMv.visitEnd()

        cw.visitEnd()
        return containerClassName to cw.toByteArray()
    }

    /**
     * Generates the Instance class for a metamodel class.
     *
     * @param classData The class definition.
     * @param metamodelPath The metamodel path for namespacing.
     * @param classMap Map of all classes for inheritance lookup.
     * @param metamodelData Full metamodel for association lookup.
     * @return Pair of (class internal name, bytecode).
     */
    private fun generateInstanceClass(
        classData: ClassData,
        metamodelPath: String,
        classMap: Map<String, ClassData>,
        metamodelData: MetamodelData
    ): Pair<String, ByteArray> {
        val className = getInstanceClassName(classData.name, metamodelPath)
        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)

        val superClassName = if (classData.extends.isNotEmpty()) {
            getInstanceClassName(classData.extends.first(), metamodelPath)
        } else {
            MODEL_INSTANCE_CLASS
        }

        val accessFlags = if (classData.isAbstract) {
            Opcodes.ACC_PUBLIC or Opcodes.ACC_ABSTRACT
        } else {
            Opcodes.ACC_PUBLIC
        }

        cw.visit(
            Opcodes.V11,
            accessFlags,
            className,
            null,
            superClassName,
            null
        )

        generateConstructor(cw, className, superClassName)

        for (property in classData.properties) {
            generatePropertyGetter(cw, className, property, metamodelPath, metamodelData)
        }

        val associations = findAssociationsForClass(classData.name, metamodelData)
        for ((propertyName, targetClassName, isMultiple) in associations) {
            generateAssociationGetter(cw, className, propertyName, targetClassName, metamodelPath, isMultiple)
        }

        cw.visitEnd()
        return className to cw.toByteArray()
    }

    /**
     * Generates the constructor that delegates to super(backing).
     */
    private fun generateConstructor(cw: ClassWriter, className: String, superClassName: String) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "<init>",
            "(L$MODEL_INSTANCE_BACKING;)V",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitVarInsn(Opcodes.ALOAD, 1)
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            superClassName,
            "<init>",
            "(L$MODEL_INSTANCE_BACKING;)V",
            false
        )

        mv.visitInsn(Opcodes.RETURN)
        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates a getter method for a property.
     */
    private fun generatePropertyGetter(
        cw: ClassWriter,
        className: String,
        property: PropertyData,
        metamodelPath: String,
        metamodelData: MetamodelData
    ) {
        val isMultiple = property.multiplicity.isMultiple()
        val (returnDescriptor, returnType) = getPropertyReturnType(property, metamodelPath, isMultiple, metamodelData)
        val methodName = "get${property.name.replaceFirstChar { it.uppercase() }}"

        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            methodName,
            "()$returnDescriptor",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, MODEL_INSTANCE_CLASS, "backing", "L$MODEL_INSTANCE_BACKING;")
        mv.visitLdcInsn(property.name)
        mv.visitMethodInsn(
            Opcodes.INVOKEINTERFACE,
            MODEL_INSTANCE_BACKING,
            "getProperty",
            "(Ljava/lang/String;)Ljava/lang/Object;",
            true
        )

        emitCastAndReturn(mv, returnDescriptor, returnType, isMultiple)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates a getter method for an association.
     */
    private fun generateAssociationGetter(
        cw: ClassWriter,
        className: String,
        propertyName: String,
        targetClassName: String,
        metamodelPath: String,
        isMultiple: Boolean
    ) {
        val targetInstanceClass = getInstanceClassName(targetClassName, metamodelPath)
        val returnDescriptor = if (isMultiple) {
            "Ljava/util/List;"
        } else {
            "L$targetInstanceClass;"
        }
        val methodName = "get${propertyName.replaceFirstChar { it.uppercase() }}"

        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            methodName,
            "()$returnDescriptor",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, MODEL_INSTANCE_CLASS, "backing", "L$MODEL_INSTANCE_BACKING;")
        mv.visitLdcInsn(propertyName)
        mv.visitMethodInsn(
            Opcodes.INVOKEINTERFACE,
            MODEL_INSTANCE_BACKING,
            "getProperty",
            "(Ljava/lang/String;)Ljava/lang/Object;",
            true
        )

        if (isMultiple) {
            mv.visitTypeInsn(Opcodes.CHECKCAST, "java/util/List")
        } else {
            mv.visitTypeInsn(Opcodes.CHECKCAST, targetInstanceClass)
        }
        mv.visitInsn(Opcodes.ARETURN)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Determines the return type descriptor and cast type for a property.
     */
    private fun getPropertyReturnType(
        property: PropertyData,
        metamodelPath: String,
        isMultiple: Boolean,
        metamodelData: MetamodelData
    ): Pair<String, String?> {
        if (isMultiple) {
            return "Ljava/util/List;" to "java/util/List"
        }

        val primitiveType = property.primitiveType
        val enumType = property.enumType

        return when {
            primitiveType != null -> when (primitiveType.lowercase()) {
                "string" -> "Ljava/lang/String;" to "java/lang/String"
                "int", "integer" -> "Ljava/lang/Integer;" to "java/lang/Integer"
                "long" -> "Ljava/lang/Long;" to "java/lang/Long"
                "float" -> "Ljava/lang/Float;" to "java/lang/Float"
                "double" -> "Ljava/lang/Double;" to "java/lang/Double"
                "boolean" -> "Ljava/lang/Boolean;" to "java/lang/Boolean"
                else -> "Ljava/lang/Object;" to "java/lang/Object"
            }
            enumType != null -> {
                val enumValueClass = ScriptEnumBytecodeGenerator.getEnumValueClassName(
                    enumType,
                    metamodelPath
                )
                "L$enumValueClass;" to enumValueClass
            }
            else -> "Ljava/lang/Object;" to "java/lang/Object"
        }
    }

    /**
     * Emits cast and return instructions based on the return type.
     */
    private fun emitCastAndReturn(
        mv: org.objectweb.asm.MethodVisitor,
        returnDescriptor: String,
        returnType: String?,
        isMultiple: Boolean
    ) {
        if (returnType != null) {
            mv.visitTypeInsn(Opcodes.CHECKCAST, returnType)
        }
        mv.visitInsn(Opcodes.ARETURN)
    }

    /**
     * Finds associations where the given class is one of the ends.
     *
     * @return List of (propertyName, targetClassName, isMultiple) tuples
     */
    private fun findAssociationsForClass(
        className: String,
        metamodelData: MetamodelData
    ): List<Triple<String, String, Boolean>> {
        val result = mutableListOf<Triple<String, String, Boolean>>()

        for (assoc in metamodelData.associations) {
            if (assoc.source.className == className && assoc.source.name != null) {
                result.add(
                    Triple(
                        assoc.source.name!!,
                        assoc.target.className,
                        assoc.source.multiplicity.isMultiple()
                    )
                )
            }
            if (assoc.target.className == className && assoc.target.name != null) {
                result.add(
                    Triple(
                        assoc.target.name!!,
                        assoc.source.className,
                        assoc.target.multiplicity.isMultiple()
                    )
                )
            }
        }

        return result
    }

    /**
     * Gets the internal class name for an Instance class.
     *
     * @param className The metamodel class name.
     * @param metamodelPath The metamodel path.
     * @return JVM internal class name.
     */
    fun getInstanceClassName(className: String, metamodelPath: String): String {
        val sanitizedPath = sanitizePath(metamodelPath)
        return "$INSTANCE_PACKAGE/${sanitizedPath}_${className}Instance"
    }

    /**
     * Gets the internal class name for a class container class.
     *
     * @param className The metamodel class name.
     * @param metamodelPath The metamodel path.
     * @return JVM internal class name.
     */
    fun getClassContainerClassName(className: String, metamodelPath: String): String {
        val sanitizedPath = sanitizePath(metamodelPath)
        return "$CONTAINER_PACKAGE/${sanitizedPath}_${className}ClassContainer"
    }

    /**
     * Sanitizes a path for use in a class name.
     */
    private fun sanitizePath(path: String): String {
        return buildString {
            for (char in path) {
                when {
                    char.isLetterOrDigit() -> append(char)
                    else -> append("_${char.code.toString(16).uppercase().padStart(2, '0')}")
                }
            }
        }
    }
}
