package com.mdeo.script.compiler.model

import com.mdeo.expression.ast.types.EnumData
import com.mdeo.expression.ast.types.MetamodelData
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes

/**
 * Generates JVM bytecode for enum types from metamodel data.
 *
 * For each enum in the metamodel, two JVM classes are generated:
 *
 * 1. **EnumValue class** (`<EnumName>EnumValue`):
 *    A final class representing individual enum values.
 *    - Has a `entry: String` field storing the entry name
 *    - Implements `toString()` returning the entry name
 *    - Implements `equals()` and `hashCode()` based on the entry field
 *
 * 2. **Enum container class** (`<EnumName>Enum`):
 *    A container class with static fields for each enum entry.
 *    - Each entry is a pre-constructed singleton of the EnumValue class
 *    - Property access `Color.RED` loads the static field
 *
 * Example: For `enum Color { RED, GREEN, BLUE }`:
 * - `ColorEnumValue` - class with `entry` field
 * - `ColorEnum` - class with `RED`, `GREEN`, `BLUE` static fields
 */
object ScriptEnumBytecodeGenerator {

    /**
     * Internal class name for EnumValue classes.
     */
    private const val ENUM_VALUE_PACKAGE = "com/mdeo/script/generated/model/enum"

    /**
     * Result of enum bytecode generation containing both class types.
     *
     * @param enumValueBytecodes Map of enum value class internal name to bytecode
     * @param enumContainerBytecodes Map of enum container class internal name to bytecode
     */
    data class EnumBytecodeResult(
        val enumValueBytecodes: Map<String, ByteArray>,
        val enumContainerBytecodes: Map<String, ByteArray>
    ) {
        /**
         * Gets all bytecodes combined.
         */
        fun allBytecodes(): Map<String, ByteArray> =
            enumValueBytecodes + enumContainerBytecodes
    }

    /**
     * Generates bytecode for all enums in the metamodel.
     *
     * Metamodel enum names are assumed to be globally unique, so the generated JVM class names
     * do not include any path component.
     *
     * @param metamodelData The metamodel containing enum definitions.
     * @return EnumBytecodeResult containing generated bytecodes.
     */
    fun generateEnumBytecodes(
        metamodelData: MetamodelData,
    ): EnumBytecodeResult {
        val enumValueBytecodes = mutableMapOf<String, ByteArray>()
        val enumContainerBytecodes = mutableMapOf<String, ByteArray>()

        for (enumData in metamodelData.enums) {
            val (valueClassName, valueBytecode) = generateEnumValueClass(enumData)
            val (containerClassName, containerBytecode) = generateEnumContainerClass(
                enumData,
                valueClassName
            )

            enumValueBytecodes[valueClassName] = valueBytecode
            enumContainerBytecodes[containerClassName] = containerBytecode
        }

        return EnumBytecodeResult(enumValueBytecodes, enumContainerBytecodes)
    }

    /**
     * Generates the EnumValue class for an enum.
     *
     * @param enumData The enum definition.
     * @return Pair of (class internal name, bytecode).
     */
    private fun generateEnumValueClass(
        enumData: EnumData,
    ): Pair<String, ByteArray> {
        val className = getEnumValueClassName(enumData.name)
        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)

        cw.visit(
            Opcodes.V11,
            Opcodes.ACC_PUBLIC or Opcodes.ACC_FINAL,
            className,
            null,
            "java/lang/Object",
            null
        )

        cw.visitField(
            Opcodes.ACC_PRIVATE or Opcodes.ACC_FINAL,
            "entry",
            "Ljava/lang/String;",
            null,
            null
        )?.visitEnd()

        generateEnumValueConstructor(cw, className)

        generateGetEntryMethod(cw, className)

        generateToStringMethod(cw, className)

        generateEqualsMethod(cw, className)

        generateHashCodeMethod(cw, className)

        cw.visitEnd()
        return className to cw.toByteArray()
    }

    /**
     * Generates the constructor for EnumValue class.
     */
    private fun generateEnumValueConstructor(cw: ClassWriter, className: String) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "<init>",
            "(Ljava/lang/String;)V",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false)

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitVarInsn(Opcodes.ALOAD, 1)
        mv.visitFieldInsn(Opcodes.PUTFIELD, className, "entry", "Ljava/lang/String;")

        mv.visitInsn(Opcodes.RETURN)
        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates the getEntry() method.
     */
    private fun generateGetEntryMethod(cw: ClassWriter, className: String) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "getEntry",
            "()Ljava/lang/String;",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, className, "entry", "Ljava/lang/String;")
        mv.visitInsn(Opcodes.ARETURN)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates the toString() method returning the entry name.
     */
    private fun generateToStringMethod(cw: ClassWriter, className: String) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "toString",
            "()Ljava/lang/String;",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, className, "entry", "Ljava/lang/String;")
        mv.visitInsn(Opcodes.ARETURN)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates the equals() method comparing entry fields.
     */
    private fun generateEqualsMethod(cw: ClassWriter, className: String) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "equals",
            "(Ljava/lang/Object;)Z",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitVarInsn(Opcodes.ALOAD, 1)
        val notSameRef = org.objectweb.asm.Label()
        mv.visitJumpInsn(Opcodes.IF_ACMPNE, notSameRef)
        mv.visitInsn(Opcodes.ICONST_1)
        mv.visitInsn(Opcodes.IRETURN)

        mv.visitLabel(notSameRef)
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null)

        mv.visitVarInsn(Opcodes.ALOAD, 1)
        mv.visitTypeInsn(Opcodes.INSTANCEOF, className)
        val isInstance = org.objectweb.asm.Label()
        mv.visitJumpInsn(Opcodes.IFNE, isInstance)
        mv.visitInsn(Opcodes.ICONST_0)
        mv.visitInsn(Opcodes.IRETURN)

        mv.visitLabel(isInstance)
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null)

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, className, "entry", "Ljava/lang/String;")
        mv.visitVarInsn(Opcodes.ALOAD, 1)
        mv.visitTypeInsn(Opcodes.CHECKCAST, className)
        mv.visitFieldInsn(Opcodes.GETFIELD, className, "entry", "Ljava/lang/String;")
        mv.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            "java/lang/String",
            "equals",
            "(Ljava/lang/Object;)Z",
            false
        )
        mv.visitInsn(Opcodes.IRETURN)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates the hashCode() method based on entry field.
     */
    private fun generateHashCodeMethod(cw: ClassWriter, className: String) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "hashCode",
            "()I",
            null,
            null
        )
        mv.visitCode()

        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, className, "entry", "Ljava/lang/String;")
        mv.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            "java/lang/String",
            "hashCode",
            "()I",
            false
        )
        mv.visitInsn(Opcodes.IRETURN)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates the Enum container class with static fields for each entry.
     *
     * @param enumData The enum definition.
     * @param valueClassName The internal name of the corresponding EnumValue class.
     * @return Pair of (class internal name, bytecode).
     */
    private fun generateEnumContainerClass(
        enumData: EnumData,
        valueClassName: String
    ): Pair<String, ByteArray> {
        val className = getEnumContainerClassName(enumData.name)
        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)

        cw.visit(
            Opcodes.V11,
            Opcodes.ACC_PUBLIC or Opcodes.ACC_FINAL,
            className,
            null,
            "java/lang/Object",
            null
        )

        for (entry in enumData.entries) {
            cw.visitField(
                Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC or Opcodes.ACC_FINAL,
                entry,
                "L$valueClassName;",
                null,
                null
            )?.visitEnd()
        }

        cw.visitField(
            Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC or Opcodes.ACC_FINAL,
            "INSTANCE",
            "L$className;",
            null,
            null
        )?.visitEnd()

        generateStaticInitializer(cw, className, valueClassName, enumData.entries)

        generatePrivateConstructor(cw)

        cw.visitEnd()
        return className to cw.toByteArray()
    }

    /**
     * Generates the static initializer that creates enum value singletons.
     */
    private fun generateStaticInitializer(
        cw: ClassWriter,
        containerClassName: String,
        valueClassName: String,
        entries: List<String>
    ) {
        val mv = cw.visitMethod(
            Opcodes.ACC_STATIC,
            "<clinit>",
            "()V",
            null,
            null
        )
        mv.visitCode()

        for (entry in entries) {
            mv.visitTypeInsn(Opcodes.NEW, valueClassName)
            mv.visitInsn(Opcodes.DUP)
            mv.visitLdcInsn(entry)
            mv.visitMethodInsn(
                Opcodes.INVOKESPECIAL,
                valueClassName,
                "<init>",
                "(Ljava/lang/String;)V",
                false
            )

            mv.visitFieldInsn(
                Opcodes.PUTSTATIC,
                containerClassName,
                entry,
                "L$valueClassName;"
            )
        }

        mv.visitTypeInsn(Opcodes.NEW, containerClassName)
        mv.visitInsn(Opcodes.DUP)
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, containerClassName, "<init>", "()V", false)
        mv.visitFieldInsn(Opcodes.PUTSTATIC, containerClassName, "INSTANCE", "L$containerClassName;")

        mv.visitInsn(Opcodes.RETURN)
        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Generates a private constructor to prevent instantiation.
     */
    private fun generatePrivateConstructor(cw: ClassWriter) {
        val mv = cw.visitMethod(
            Opcodes.ACC_PRIVATE,
            "<init>",
            "()V",
            null,
            null
        )
        mv.visitCode()
        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false)
        mv.visitInsn(Opcodes.RETURN)
        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Gets the internal class name for an EnumValue class.
     * Metamodel enum names are globally unique, so no path prefix is needed.
     *
     * @param enumName The enum name.
     * @return JVM internal class name.
     */
    fun getEnumValueClassName(enumName: String): String {
        return "$ENUM_VALUE_PACKAGE/${enumName}EnumValue"
    }

    /**
     * Gets the internal class name for an Enum container class.
     * Metamodel enum names are globally unique, so no path prefix is needed.
     *
     * @param enumName The enum name.
     * @return JVM internal class name.
     */
    fun getEnumContainerClassName(enumName: String): String {
        return "$ENUM_VALUE_PACKAGE/${enumName}Enum"
    }
}
