package com.mdeo.modeltransformation.runtime.match

import com.mdeo.expression.ast.expressions.TypedExpression
import com.mdeo.expression.ast.types.ClassTypeRef
import com.mdeo.modeltransformation.ast.EdgeLabelUtils
import com.mdeo.modeltransformation.ast.patterns.TypedPattern
import com.mdeo.modeltransformation.ast.patterns.TypedPatternObjectInstanceElement
import com.mdeo.modeltransformation.ast.patterns.TypedPatternLinkElement
import com.mdeo.modeltransformation.ast.patterns.TypedPatternVariableElement
import com.mdeo.modeltransformation.ast.patterns.TypedPatternWhereClauseElement
import com.mdeo.modeltransformation.ast.patterns.TypedPatternPropertyAssignment
import com.mdeo.modeltransformation.compiler.CompilationContext
import com.mdeo.modeltransformation.compiler.CompilationResult
import com.mdeo.modeltransformation.compiler.LabelIdGenerator
import com.mdeo.modeltransformation.compiler.SequentialLabelIdGenerator
import com.mdeo.modeltransformation.compiler.VariableBinding
import com.mdeo.modeltransformation.graph.VertexRef
import com.mdeo.modeltransformation.compiler.expressions.EqualityCompilerUtil
import com.mdeo.modeltransformation.runtime.TransformationExecutionContext
import com.mdeo.modeltransformation.runtime.TransformationEngine
import org.apache.tinkerpop.gremlin.process.traversal.P
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.`__` as AnonymousTraversal
import org.apache.tinkerpop.gremlin.structure.Vertex
import org.apache.tinkerpop.gremlin.structure.VertexProperty

/**
 * Unified executor that combines pattern matching and modifications in a single Gremlin query.
 *
 * This executor builds a single Gremlin traversal that:
 * 1. Matches the pattern using match() step
 * 2. Applies limit for single match or unlimited for foreach
 * 3. Creates new vertices using addV()
 * 4. Sets properties on vertices
 * 5. Creates edges using addE()
 * 6. Deletes edges and vertices using drop()
 *
 * The design ensures atomicity by executing all operations in one traversal,
 * avoiding separate match and modification phases.
 *
 * ## Traversal Expression Compilation
 * Where clauses and property values are compiled using the traversal compiler registry.
 * This ensures expressions are converted to pure Gremlin traversals without Java lambdas.
 *
 * ## Label ID Generation
 * A single [SequentialLabelIdGenerator] instance is owned by each [MatchExecutor] and
 * shared with every [CompilationContext] produced during traversal construction. This
 * prevents step-label collisions between labels generated by expression compilers and
 * labels generated directly by the executor.
 */
class MatchExecutor {

    companion object {
        /**
         * Default limit for single match operations.
         */
        const val DEFAULT_LIMIT = 1L

        /** 
         * Value indicating no limit (for foreach operations).
         */
        const val UNLIMITED = -1L

        /**
         *Anchor label for match clauses to ensure all clauses are connected.
         */
        private const val ANCHOR_LABEL = "_"
    }

    /**
     * Shared label ID generator for this executor.
     *
     * Passed into every [CompilationContext] so that compiler-generated labels and
     * executor-generated labels share a single counter, eliminating the risk of
     * collision between the two sources.
     */
    private val labelIdGenerator: LabelIdGenerator = SequentialLabelIdGenerator()

    /**
     * Executes a pattern match with modifications, returning the first match.
     *
     * @param pattern The pattern to match against the graph
     * @param context The current transformation execution context
     * @param engine The transformation engine providing access to the graph and compilers
     * @return A MatchResult containing the matched bindings, or NoMatch if no match is found
     */
    fun executeMatch(
        pattern: TypedPattern,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): MatchResult {
        return executeMatchWithLimit(pattern, context, engine, DEFAULT_LIMIT).firstOrNull()
            ?: MatchResult.NoMatch("No match found")
    }

    /**
     * Executes a pattern match with modifications, returning all matches.
     *
     * @param pattern The pattern to match against the graph
     * @param context The current transformation execution context
     * @param engine The transformation engine providing access to the graph and compilers
     * @return A list of all MatchResult.Matched instances found in the graph
     */
    fun executeMatchAll(
        pattern: TypedPattern,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): List<MatchResult.Matched> {
        return executeMatchWithLimit(pattern, context, engine, UNLIMITED)
    }

    /**
     * Executes pattern match with a specified limit.
     *
     * If the engine is running in non-deterministic mode ([TransformationEngine.deterministic] is
     * false), this method first calls [com.mdeo.modeltransformation.graph.ModelGraph.resetNondeterminism]
     * on the engine's model graph before building and executing the traversal. Resetting before
     * every individual match (rather than once per transformation) ensures that different match
     * steps within the same transformation can each explore a fresh, independently-shuffled
     * iteration order — preventing earlier matches from artificially constraining the outcomes
     * of later ones.
     *
     * @param pattern The pattern to match.
     * @param context The current execution context.
     * @param engine The transformation engine.
     * @param limit Maximum number of matches (-1 for unlimited).
     * @return List of match results with modifications applied.
     */
    fun executeMatchWithLimit(
        pattern: TypedPattern,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        limit: Long
    ): List<MatchResult.Matched> {
        if (!engine.deterministic) {
            engine.modelGraph.resetNondeterminism()
        }

        val elements = PatternCategories.from(pattern)

        val scope = context.variableScope
        for (name in elements.allInstanceNames) {
            if (scope.getVariable(name) == null) {
                scope.setBinding(name, VariableBinding.InstanceBinding(vertexRef = null))
            }
        }

        return executeUnifiedTraversal(elements, context, engine, limit)
    }

    /**
     * Executes the unified traversal combining match and modifications.
     *
     * Analyzes the pattern elements, builds match clauses, constructs a unified traversal,
     * and executes it to return matched results with all modifications applied.
     *
     * @param elements Categorized pattern elements (instances, links, variables, etc.)
     * @param context The transformation execution context with variable bindings
     * @param engine The transformation engine providing graph access and compilers
     * @param limit Maximum number of matches to return (-1 for unlimited)
     * @return List of matched results with instance mappings and node classifications
     */
    private fun executeUnifiedTraversal(
        elements: PatternCategories,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        limit: Long
    ): List<MatchResult.Matched> {
        val compilationContext = newCompilationContext(engine, context)

        for (variableElement in elements.variables) {
            val variableName = variableElement.variable.name
            val variableLabel = VariableBinding.variableLabel(variableName)
            context.variableScope.setBinding(variableName, VariableBinding.LabelBinding(variableLabel))
        }

        val analyzer = MatchAnalyzer(context.variableScope)
        for (element in elements.variables) {
            analyzer.analyzeVariable(element)
        }
        for (element in elements.whereClauses) {
            analyzer.analyzeWhereClause(element)
        }
        for (instance in elements.matchableInstances + elements.createInstances + elements.deleteInstances) {
            analyzer.analyzeObjectInstance(instance)
        }
        for (link in elements.matchableLinks + elements.createLinks + elements.deleteLinks + elements.forbidLinks + elements.requireLinks) {
            analyzer.analyzeLink(link)
        }

        val referencedInstances = analyzer.getReferencedInstances()

        val allMatchableInstances = elements.matchableInstances + elements.deleteInstances
        val allMatchableLinks = elements.matchableLinks + elements.deleteLinks

        val matchBuildResult = buildMatchClauses(
            allMatchableInstances, allMatchableLinks, elements.variables,
            referencedInstances, context, engine, compilationContext
        )

        val traversal = buildUnifiedTraversal(
            elements, matchBuildResult.clauses, matchBuildResult.compiledVariables,
            context, engine, limit, compilationContext
        )
        val matchedInstanceNames = allMatchableInstances.map { it.objectInstance.name }
        return executeTraversalAndExtract(traversal, elements, context, engine, matchedInstanceNames)
    }

    /**
     * Builds the unified Gremlin traversal.
     *
     * Uses g.inject(null).as("_") as the anchor point for the match() step.
     * This ensures all match clauses can connect through the anchor, solving
     * the "unsolvable match pattern" issue for disconnected patterns.
     *
     * @param elements Categorized pattern elements (instances, links, variables, where clauses)
     * @param matchClauses Array of match clause traversals to combine
     * @param compiledVariables Compiled variable expressions indexed by variable label
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param limit Maximum number of matches (-1 for unlimited)
     * @param compilationContext The shared compilation context
     * @return A unified traversal that executes match, modifications, and returns selected values
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildUnifiedTraversal(
        elements: PatternCategories,
        matchClauses: Array<GraphTraversal<Any, Any>>,
        compiledVariables: CompiledVariables,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        limit: Long,
        compilationContext: CompilationContext
    ): GraphTraversal<Vertex, Any> {
        val g = engine.traversalSource

        val allMatchableInstances = elements.matchableInstances + elements.deleteInstances

        var traversal: GraphTraversal<Vertex, Map<String, Any>> = if (matchClauses.isEmpty()) {
            var t = g.inject(emptyMap<String, Any>()) as GraphTraversal<Vertex, Map<String, Any>>
            t = addIslandConstraints(t, elements, context, engine)
            t = addPropertyWhereConstraints(t, allMatchableInstances, context, engine)
            t = addWhereClauseConstraints(t, elements.whereClauses, context, engine)
            t = addInjectiveMatchConstraints(t, allMatchableInstances, engine)
            t
        } else {
            var t = buildMatchStep(
                g.inject(emptyMap<String, Any>()).`as`(ANCHOR_LABEL) as GraphTraversal<Vertex, Vertex>,
                matchClauses
            )
            t = addIslandConstraints(t, elements, context, engine)
            t = addPropertyWhereConstraints(t, allMatchableInstances, context, engine)
            t = addWhereClauseConstraints(t, elements.whereClauses, context, engine)
            t = addInjectiveMatchConstraints(t, allMatchableInstances, engine)
            t
        }

        traversal = applyLimit(traversal, limit)

        val matchedInstanceNames = elements.matchableInstances.map { it.objectInstance.name }
        traversal = addCreateVertexSteps(traversal, elements.createInstances, context, engine, matchedInstanceNames, compilationContext)

        traversal = addPropertyUpdateSteps(traversal, elements, context, engine, matchedInstanceNames, compilationContext)
        val currentPatternInstanceNames = elements.allInstanceNames.toSet()
        traversal = addCreateEdgeSteps(traversal, elements.createLinks, context, engine, currentPatternInstanceNames)
        traversal = addDeleteSteps(traversal, elements)

        val variableLabels = elements.variables.map { VariableBinding.variableLabel(it.variable.name) }
        return addSelectStep(traversal, elements.allInstanceNames, variableLabels)
    }

    /**
     * Checks whether two class names are type-compatible, meaning one could be a
     * subtype of the other (or they are the same type). If either class name is null,
     * the instance could match any vertex, so they are always considered compatible.
     *
     * @param classNameA The class name of the first instance (nullable)
     * @param classNameB The class name of the second instance (nullable)
     * @param engine The transformation engine providing the type registry
     * @return True if the two types could potentially match the same vertex
     */
    private fun areTypesCompatible(classNameA: String?, classNameB: String?, engine: TransformationEngine): Boolean {
        if (classNameA == null || classNameB == null) return true
        val typeRefA = ClassTypeRef(`package` = engine.classPackage, type = classNameA, isNullable = false)
        val typeRefB = ClassTypeRef(`package` = engine.classPackage, type = classNameB, isNullable = false)
        return engine.typeRegistry.isSubtypeOf(typeRefA, typeRefB) || engine.typeRegistry.isSubtypeOf(typeRefB, typeRefA)
    }

    /**
     * Adds injective match constraints to ensure that all matchable and delete instances
     * bind to distinct vertices. For each pair of type-compatible instances, adds a
     * `where(stepLabel_a, P.neq(stepLabel_b))` constraint.
     *
     * @param traversal The traversal to extend with injective constraints
     * @param matchableInstances The list of matchable and delete instances
     * @param engine The transformation engine providing the type registry
     * @return The extended traversal with injective constraints added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addInjectiveMatchConstraints(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        matchableInstances: List<TypedPatternObjectInstanceElement>,
        engine: TransformationEngine
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (i in matchableInstances.indices) {
            for (j in i + 1 until matchableInstances.size) {
                val a = matchableInstances[i]
                val b = matchableInstances[j]

                if (a.objectInstance.name == b.objectInstance.name) {
                    continue
                }

                if (!areTypesCompatible(a.objectInstance.className, b.objectInstance.className, engine)) {
                    continue
                }

                result = result.where(
                    VariableBinding.stepLabel(a.objectInstance.name),
                    P.neq(VariableBinding.stepLabel(b.objectInstance.name))
                ) as GraphTraversal<Vertex, Map<String, Any>>
            }
        }

        return result
    }

    /**
     * Builds the match() step from the clauses.
     *
     * Handles both single and multiple match clauses using the appropriate overload
     * of the match() step. Gremlin requires different syntax for one vs many clauses.
     *
     * @param traversal The base traversal to append the match step to
     * @param matchClauses Array of match clause traversals
     * @return The traversal with match step applied, returning a map of matched elements
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildMatchStep(
        traversal: GraphTraversal<Vertex, Vertex>,
        matchClauses: Array<GraphTraversal<Any, Any>>
    ): GraphTraversal<Vertex, Map<String, Any>> {
        return if (matchClauses.size == 1) {
            traversal.match<Any>(matchClauses[0]) as GraphTraversal<Vertex, Map<String, Any>>
        } else {
            traversal.match<Any>(matchClauses[0], *matchClauses.drop(1).toTypedArray())
                as GraphTraversal<Vertex, Map<String, Any>>
        }
    }

    /**
     * Applies a limit to the traversal.
     *
     * Always uses `limit()` to pick the first N candidates in traversal order.
     * Non-determinism for search-based optimisation is achieved by randomizing
     * the graph's vertex order before each match step (by shuffling the nodes in the graph copy)
     * not by sampling from all matches.
     *
     * @param traversal The traversal to apply the limit to.
     * @param limit Maximum number of results to return (values <= 0 mean no limit).
     * @return The traversal with the appropriate step applied.
     */
    private fun applyLimit(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        limit: Long,
    ): GraphTraversal<Vertex, Map<String, Any>> {
        return when {
            limit <= 0 -> traversal
            else -> traversal.limit(limit) as GraphTraversal<Vertex, Map<String, Any>>
        }
    }

    /**
     * Adds addV() steps for creating new vertices with all their properties.
     *
     * @param traversal The traversal to extend with vertex creation steps
     * @param createInstances List of instance elements marked for creation
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances that can be referenced
     * @param compilationContext The shared compilation context
     * @return The extended traversal with all vertex creation steps added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addCreateVertexSteps(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        createInstances: List<TypedPatternObjectInstanceElement>,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>,
        compilationContext: CompilationContext
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (instance in createInstances) {
            val className = instance.objectInstance.className
            val name = instance.objectInstance.name

            result = result.addV(className).`as`(VariableBinding.stepLabel(name)) as GraphTraversal<Vertex, Map<String, Any>>
            result = addCreateVertexProperties(result, className, name, instance.objectInstance.properties, context, engine, matchedInstanceNames, compilationContext)
        }

        return result
    }

    /**
     * Adds all properties to a newly created vertex.
     *
     * Separates properties into:
     * - Simple scalar values: set inline with .property()
     * - Collection values: set via sideEffect with Cardinality.list
     *
     * @param traversal The traversal with the newly created vertex as current element
     * @param className The metamodel class name of the vertex being created
     * @param instanceName The name of the instance being created
     * @param properties The properties to set
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances available for reference
     * @param compilationContext The shared compilation context for expression compilation
     * @return The extended traversal
     */
    @Suppress("UNCHECKED_CAST")
    private fun addCreateVertexProperties(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        className: String?,
        instanceName: String,
        properties: List<TypedPatternPropertyAssignment>,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>,
        compilationContext: CompilationContext
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        val (listProperties, simpleProperties) = properties.filter { it.operator == "=" }.partition { property ->
            val expressionType = resolveExpressionType(property.value, engine)!!
            isCollectionType(expressionType, engine)
        }

        for (property in simpleProperties) {
            val graphKey = engine.resolvePropertyGraphKey(className, property.propertyName)
            val compilationResult = compilePropertyExpression(property.value, context, engine, matchedInstanceNames)!!
            if (compilationResult is CompilationResult.ValueResult) {
                val value = compilationResult.value
                if (value != null) {
                    result = result.property(graphKey, value)
                        as GraphTraversal<Vertex, Map<String, Any>>
                }
            } else {
                result = result.property(graphKey, compilationResult.traversal)
                    as GraphTraversal<Vertex, Map<String, Any>>
            }
        }

        for (property in listProperties) {
            val graphKey = engine.resolvePropertyGraphKey(className, property.propertyName)
            val listResult = compilePropertyExpression(property.value, context, engine, matchedInstanceNames)!!
            val listTraversal = listResult.traversal as GraphTraversal<Any, Any>
            val valueLabel = compilationContext.getUniqueId()

            result = result.sideEffect(
                listTraversal
                    .`as`(valueLabel)
                    .select<Any>(VariableBinding.stepLabel(instanceName))
                    .property(
                        VertexProperty.Cardinality.list,
                        graphKey,
                        AnonymousTraversal.select<Any, Any>(valueLabel)
                    )
            ) as GraphTraversal<Vertex, Map<String, Any>>
        }

        return result
    }

    /**
     * Adds property update steps for matched instances.
     *
     * @param traversal The traversal to extend with property update steps
     * @param elements Categorized pattern elements containing instances to update
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances available for reference
     * @param compilationContext The shared compilation context
     * @return The extended traversal with all property update steps added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addPropertyUpdateSteps(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        elements: PatternCategories,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>,
        compilationContext: CompilationContext
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (instance in elements.matchableInstances) {
            if (instance.objectInstance.modifier == "delete") continue
            result = addMatchedInstanceProperties(result, instance, context, engine, matchedInstanceNames, compilationContext)
        }

        return result
    }

    /**
     * Adds property updates for a matched instance via sideEffect.
     *
     * All property updates use sideEffect with select() to access the vertex by its label.
     * For collection properties, existing values are cleared before adding new ones.
     *
     * @param traversal The main traversal
     * @param instance The matched instance to update
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances available for reference
     * @param compilationContext The shared compilation context
     * @return The extended traversal with property update steps
     */
    @Suppress("UNCHECKED_CAST")
    private fun addMatchedInstanceProperties(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        instance: TypedPatternObjectInstanceElement,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>,
        compilationContext: CompilationContext
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal
        val name = instance.objectInstance.name
        val className = instance.objectInstance.className

        for (property in instance.objectInstance.properties) {
            if (property.operator != "=") continue

            val graphKey = engine.resolvePropertyGraphKey(className, property.propertyName)
            val expressionType = resolveExpressionType(property.value, engine)
            val isCollection = isCollectionType(expressionType, engine)

            if (isCollection) {
                val listResult = compilePropertyExpression(property.value, context, engine, matchedInstanceNames)
                if (listResult != null) {
                    result = setListPropertyViaSideEffect(result, name, graphKey, listResult, compilationContext)
                }
            } else {
                val value = getPropertyValue(property.value, context, engine, matchedInstanceNames)
                result = result.sideEffect(
                    AnonymousTraversal.select<Any, Any>(VariableBinding.stepLabel(name))
                        .property(graphKey, value)
                ) as GraphTraversal<Vertex, Map<String, Any>>
            }
        }

        return result
    }

    /**
     * Sets list property values using Cardinality.list via sideEffect.
     *
     * Clears existing property values, then evaluates the list traversal and adds each
     * emitted value as a separate property value with Cardinality.list.
     *
     * @param traversal The main traversal to extend.
     * @param instanceName The name of the instance to set the property on.
     * @param graphKey The graph property key (e.g. "prop_2").
     * @param listResult The CompilationResult that emits list element values.
     * @param compilationContext The shared compilation context for unique ID generation.
     * @return The extended traversal with sideEffect steps for list property management.
     */
    @Suppress("UNCHECKED_CAST")
    private fun setListPropertyViaSideEffect(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        instanceName: String,
        graphKey: String,
        listResult: CompilationResult,
        compilationContext: CompilationContext
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        result = result.sideEffect(
            AnonymousTraversal.select<Any, Any>(VariableBinding.stepLabel(instanceName))
                .properties<Any>(graphKey)
                .drop()
        ) as GraphTraversal<Vertex, Map<String, Any>>

        val listTraversal = listResult.traversal as GraphTraversal<Any, Any>
        val valueLabel = compilationContext.getUniqueId()

        result = result.sideEffect(
            listTraversal
                .`as`(valueLabel)
                .select<Any>(VariableBinding.stepLabel(instanceName))
                .property(
                    VertexProperty.Cardinality.list,
                    graphKey,
                    AnonymousTraversal.select<Any, Any>(valueLabel)
                )
        ) as GraphTraversal<Vertex, Map<String, Any>>

        return result
    }

    /**
     * Adds addE() steps for creating edges between matched or created instances.
     *
     * @param traversal The traversal to extend with edge creation steps
     * @param createLinks List of link elements marked for creation
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param currentPatternInstanceNames Set of instance names in the current pattern
     * @return The extended traversal with all edge creation steps added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addCreateEdgeSteps(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        createLinks: List<TypedPatternLinkElement>,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        currentPatternInstanceNames: Set<String>
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (link in createLinks) {
            val sourceName = link.link.source.objectName
            val targetName = link.link.target.objectName
            val sourceProperty = link.link.source.propertyName
            val targetProperty = link.link.target.propertyName
            val edgeLabel = EdgeLabelUtils.computeEdgeLabel(sourceProperty, targetProperty)

            val sourceTraversal = AnonymousTraversal.select<Any, Any>(VariableBinding.stepLabel(sourceName))
            val targetTraversal = AnonymousTraversal.select<Any, Any>(VariableBinding.stepLabel(targetName))

            result = result.sideEffect(
                sourceTraversal.addE(edgeLabel).to(targetTraversal)
            ) as GraphTraversal<Vertex, Map<String, Any>>
        }

        return result
    }

    /**
     * Adds delete steps for deleteInstances and deleteLinks.
     *
     * @param traversal The traversal to extend with delete operations
     * @param elements Categorized pattern elements containing delete instances
     * @return The traversal with delete steps added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addDeleteSteps(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        elements: PatternCategories
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (link in elements.deleteLinks) {
            result = addDeleteEdgeStep(result, link)
        }

        for (instance in elements.deleteInstances) {
            val name = instance.objectInstance.name
            result = result.sideEffect(
                AnonymousTraversal.select<Any, Any>(VariableBinding.stepLabel(name)).drop()
            ) as GraphTraversal<Vertex, Map<String, Any>>
        }

        return result
    }

    /**
     * Adds a step to delete an edge between two instances.
     *
     * Computes the edge label from property names and filters edges to ensure
     * only edges between the specific source and target vertices are deleted.
     *
     * @param traversal The traversal to extend with the edge deletion step
     * @param link The link element representing the edge to delete
     * @return The extended traversal with the edge deletion step added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addDeleteEdgeStep(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        link: TypedPatternLinkElement
    ): GraphTraversal<Vertex, Map<String, Any>> {
        val sourceName = link.link.source.objectName
        val targetName = link.link.target.objectName
        val sourceProperty = link.link.source.propertyName
        val targetProperty = link.link.target.propertyName
        val edgeLabel = EdgeLabelUtils.computeEdgeLabel(sourceProperty, targetProperty)

        return traversal.sideEffect(
            AnonymousTraversal.select<Any, Any>(VariableBinding.stepLabel(sourceName))
                .outE(edgeLabel)
                .where(AnonymousTraversal.inV().`as`(VariableBinding.stepLabel(targetName)))
                .drop()
        ) as GraphTraversal<Vertex, Map<String, Any>>
    }

    /**
     * Builds match clauses for the Gremlin match() step.
     *
     * Order of match clauses:
     * 1. Vertex/instance clauses (for pattern instances and referenced instances)
     * 2. Edge/link clauses
     * 3. Variable clauses
     *
     * @param instances List of object instance elements to match
     * @param links List of link elements to match
     * @param variables List of variable elements to evaluate
     * @param referencedInstances Set of instance names referenced but not explicitly matched
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param compilationContext The shared compilation context
     * @return MatchClauseBuildResult containing the clause array and compiled variables
     */
    private fun buildMatchClauses(
        instances: List<TypedPatternObjectInstanceElement>,
        links: List<TypedPatternLinkElement>,
        variables: List<TypedPatternVariableElement>,
        referencedInstances: Set<String>,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        compilationContext: CompilationContext
    ): MatchClauseBuildResult {
        val clauses = mutableListOf<GraphTraversal<Any, Any>>()

        for (instance in instances) {
            val binding = context.variableScope.getVariable(instance.objectInstance.name)
            val vertexId = (binding as? VariableBinding.InstanceBinding)?.vertexId

            if (vertexId != null) {
                clauses.add(buildIdVertexMatchClause(vertexId, instance.objectInstance.name))
            } else if (instance.objectInstance.className != null) {
                clauses.add(buildVertexMatchClauses(instance, context, engine))
            } else {
                continue
            }
        }

        val instanceNames = instances.map { it.objectInstance.name }.toSet()
        for (referencedInstance in referencedInstances) {
            if (referencedInstance in instanceNames) {
                continue
            }
            val binding = context.variableScope.getVariable(referencedInstance)
            val vertexId = (binding as? VariableBinding.InstanceBinding)?.vertexId
            if (vertexId != null) {
                clauses.add(buildIdVertexMatchClause(vertexId, referencedInstance))
            }
        }

        for (link in links) {
            clauses.add(buildEdgeMatchClause(link))
        }

        val compiledVariablesMap = mutableMapOf<String, CompilationResult>()
        for (variableElement in variables) {
            val variableName = variableElement.variable.name
            val variableLabel = VariableBinding.variableLabel(variableName)
            val (variableClause, compilationResult) = buildVariableMatchClause(variableElement, variableLabel, context, engine, compilationContext)
            clauses.add(variableClause)
            compiledVariablesMap[variableLabel] = compilationResult
        }

        @Suppress("UNCHECKED_CAST")
        return MatchClauseBuildResult(
            clauses = clauses.toTypedArray(),
            compiledVariables = CompiledVariables(compiledVariablesMap)
        )
    }

    /**
     * Builds a match clause for a variable.
     *
     * The variable expression is compiled to a traversal and labeled.
     * The result is: anchor.expression.as(variableLabel)
     *
     * @param variableElement The variable element to compile
     * @param variableLabel The label to use for the compiled variable in the traversal
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param compilationContext The shared compilation context
     * @return A pair of (match clause traversal, compilation result)
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildVariableMatchClause(
        variableElement: TypedPatternVariableElement,
        variableLabel: String,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        compilationContext: CompilationContext
    ): Pair<GraphTraversal<Any, Any>, CompilationResult> {
        val anchorTraversal = AnonymousTraversal.`as`<Any>(ANCHOR_LABEL)

        val compilationResult = engine.expressionCompilerRegistry.compile(
            variableElement.variable.value,
            compilationContext,
            anchorTraversal
        )

        val traversal = compilationResult.traversal.`as`(variableLabel) as GraphTraversal<Any, Any>

        return Pair(traversal, compilationResult)
    }

    /**
     * Builds a vertex match clause for an object instance using the anchor pattern.
     *
     * If [instance] has a className, matches vertices by label and applies constant
     * property comparisons (== operator) inline. Non-constant property constraints are
     * handled separately via [addPropertyWhereConstraints].
     *
     * If className is null, references a previously-bound instance by name and applies
     * constant property comparisons.
     *
     * @param instance The object instance element to match
     * @param context The transformation execution context for property compilation
     * @param engine The transformation engine
     * @return A match clause traversal for the vertex with property filters
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildVertexMatchClauses(
        instance: TypedPatternObjectInstanceElement,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Any, Any> {
        val name = instance.objectInstance.name
        val className = instance.objectInstance.className

        var clause: GraphTraversal<Any, Any> = if (className == null) {
            AnonymousTraversal.`as`<Any>(ANCHOR_LABEL)
                .select<Any>(VariableBinding.stepLabel(name))
                .`as`(VariableBinding.stepLabel(name)) as GraphTraversal<Any, Any>
        } else {
            AnonymousTraversal.`as`<Any>(ANCHOR_LABEL)
                .V()
                .hasLabel(className)
                .`as`(VariableBinding.stepLabel(name)) as GraphTraversal<Any, Any>
        }

        for (property in instance.objectInstance.properties) {
            if (property.operator == "==") {
                if (isCollectionType(resolveExpressionType(property.value, engine), engine)) {
                    throw IllegalArgumentException("List properties cannot be used in match clause comparisons (== operator) - not supported in Gremlin match patterns")
                }

                val compilationResult = compilePropertyExpression(property.value, context, engine, emptyList())
                    ?: throw IllegalStateException("Failed to compile property expression for ${property.propertyName}")

                if (compilationResult is CompilationResult.ValueResult) {
                    val graphKey = engine.resolvePropertyGraphKey(className, property.propertyName)
                    clause = clause.has(graphKey, compilationResult.value) as GraphTraversal<Any, Any>
                }
            }
        }

        return clause
    }

    /**
     * Builds a vertex match clause for a pre-bound instance using V(id).
     *
     * @param vertexId The vertex ID to match directly
     * @param name The instance name to use as the step label
     * @return A match clause traversal starting from the specified vertex ID
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildIdVertexMatchClause(
        vertexId: Any,
        name: String
    ): GraphTraversal<Any, Any> {
        return AnonymousTraversal.`as`<Any>(ANCHOR_LABEL)
            .V(vertexId)
            .`as`(VariableBinding.stepLabel(name)) as GraphTraversal<Any, Any>
    }

    /**
     * Builds an edge match clause for a link.
     *
     * Computes the edge label from source and target property names using EdgeLabelUtils.
     *
     * @param link The link element representing the edge to match
     * @return A match clause traversal for the edge from source to target
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildEdgeMatchClause(link: TypedPatternLinkElement): GraphTraversal<Any, Any> {
        val sourceName = link.link.source.objectName
        val targetName = link.link.target.objectName
        val sourceProperty = link.link.source.propertyName
        val targetProperty = link.link.target.propertyName
        val edgeLabel = EdgeLabelUtils.computeEdgeLabel(sourceProperty, targetProperty)

        return AnonymousTraversal.`as`<Any>(VariableBinding.stepLabel(sourceName))
            .out(edgeLabel)
            .`as`(VariableBinding.stepLabel(targetName)) as GraphTraversal<Any, Any>
    }

    /**
     * Adds island-based constraints for both forbid and require application conditions.
     *
     * Groups forbid instances/links and require instances/links into connected component
     * "islands" using [IslandGrouper], then generates a single constraint per island.
     *
     * Also handles "orphan" links whose both endpoints are matched (not island) nodes —
     * these receive individual constraints without island grouping.
     *
     * - Forbid islands produce `not(...)` — the match fails if the island subpattern is found.
     * - Require islands produce `where(...)` — the match fails if the island subpattern is NOT found.
     *
     * @param traversal The traversal to extend with island constraints
     * @param elements Categorized pattern elements containing forbid/require instances and links
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @return The extended traversal with all island constraints appended
     */
    @Suppress("UNCHECKED_CAST")
    private fun addIslandConstraints(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        elements: PatternCategories,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        val matchableNames = (elements.matchableInstances + elements.deleteInstances)
            .map { it.objectInstance.name }.toSet()

        val forbidIslands = IslandGrouper.groupIntoIslands(elements.forbidInstances, elements.forbidLinks)
        for (island in forbidIslands) {
            result = addSingleIslandConstraint(result, island, matchableNames, isNegative = true, context, engine)
        }

        result = addOrphanLinkConstraints(result, elements.forbidInstances, elements.forbidLinks, matchableNames, isNegative = true)

        val requireIslands = IslandGrouper.groupIntoIslands(elements.requireInstances, elements.requireLinks)
        for (island in requireIslands) {
            result = addSingleIslandConstraint(result, island, matchableNames, isNegative = false, context, engine)
        }

        result = addOrphanLinkConstraints(result, elements.requireInstances, elements.requireLinks, matchableNames, isNegative = false)

        return result
    }

    /**
     * Adds constraints for "orphan" links — links whose both endpoints are matched
     * nodes, not members of any island instance list.
     *
     * These links represent constraints between already-matched nodes (e.g., forbid an
     * edge between two nodes that are both in the main match). Each such link generates
     * its own constraint.
     *
     * @param traversal The traversal to extend
     * @param conditionInstances The forbid or require instances
     * @param conditionLinks The forbid or require links
     * @param matchableNames Names of matchable/delete instances
     * @param isNegative True for forbid (NAC), false for require (PAC)
     * @return The extended traversal with orphan link constraints appended
     */
    @Suppress("UNCHECKED_CAST")
    private fun addOrphanLinkConstraints(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        conditionInstances: List<TypedPatternObjectInstanceElement>,
        conditionLinks: List<TypedPatternLinkElement>,
        matchableNames: Set<String>,
        isNegative: Boolean
    ): GraphTraversal<Vertex, Map<String, Any>> {
        val conditionInstanceNames = conditionInstances.map { it.objectInstance.name }.toSet()
        var result = traversal

        for (link in conditionLinks) {
            val sourceName = link.link.source.objectName
            val targetName = link.link.target.objectName
            val sourceIsOrphan = sourceName !in conditionInstanceNames && sourceName in matchableNames
            val targetIsOrphan = targetName !in conditionInstanceNames && targetName in matchableNames

            if (sourceIsOrphan && targetIsOrphan) {
                val edgeLabel = EdgeLabelUtils.computeEdgeLabel(
                    link.link.source.propertyName, link.link.target.propertyName
                )
                val innerTraversal = AnonymousTraversal.`as`<Any>(VariableBinding.stepLabel(sourceName))
                    .out(edgeLabel)
                    .`as`(VariableBinding.stepLabel(targetName)) as GraphTraversal<Any, Any>

                result = if (isNegative) {
                    result.where(AnonymousTraversal.not<Any>(innerTraversal))
                        as GraphTraversal<Vertex, Map<String, Any>>
                } else {
                    result.where(innerTraversal)
                        as GraphTraversal<Vertex, Map<String, Any>>
                }
            }
        }

        return result
    }

    /**
     * Appends one island constraint to the traversal.
     *
     * Delegates to [addDisconnectedIslandConstraint] for islands with no links.
     * For connected islands, builds a chain traversal and wraps it as a
     * negative (`not(...)`) or positive (`where(...)`) filter.
     *
     * @param traversal The traversal to extend
     * @param island The island whose constraint to generate
     * @param matchableNames Names of matchable/delete instances available as step labels
     * @param isNegative True for forbid (NAC), false for require (PAC)
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @return The extended traversal with the island constraint appended
     */
    @Suppress("UNCHECKED_CAST")
    private fun addSingleIslandConstraint(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        island: Island,
        matchableNames: Set<String>,
        isNegative: Boolean,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Vertex, Map<String, Any>> {
        if (island.links.isEmpty()) {
            return addDisconnectedIslandConstraint(traversal, island, isNegative, context, engine)
        }

        val islandInstanceNames = island.instances.map { it.objectInstance.name }.toSet()
        val islandClassMap = island.instances.mapNotNull { instance ->
            val className = instance.objectInstance.className
            if (className != null) instance.objectInstance.name to className else null
        }.toMap()

        val innerTraversal = buildIslandChainTraversal(island, islandInstanceNames, islandClassMap, matchableNames, context, engine)
            ?: return traversal

        return if (isNegative) {
            traversal.where(AnonymousTraversal.not<Any>(innerTraversal))
                as GraphTraversal<Vertex, Map<String, Any>>
        } else {
            traversal.where(innerTraversal)
                as GraphTraversal<Vertex, Map<String, Any>>
        }
    }

    /**
     * Builds a flat Gremlin traversal chain that walks the island's connectivity graph.
     *
     * Uses BFS starting from an anchor node (a matched node referenced by island links)
     * to order the island's links into a traversable chain. Each link extends the chain
     * with `.out(edge).hasLabel(class)` (or `.in(edge)` for reverse direction).
     *
     * When the chain needs to return to a previously visited node to explore a different
     * branch, `.select(nodeName)` is used for backtracking. Every node reached by the BFS
     * is labeled unconditionally via `.as(stepLabel(nodeName))` to support backtracking in
     * branching (tree-shaped) island patterns.
     *
     * @param island The island containing instances and links
     * @param islandInstanceNames Set of names of instances in this island
     * @param islandClassMap Map from island instance name to its class name
     * @param matchableNames Set of matched/delete instance names (potential anchors)
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @return A traversal chain starting from an anchor, or null if no anchor is found
     */
    @Suppress("UNCHECKED_CAST")
    private fun buildIslandChainTraversal(
        island: Island,
        islandInstanceNames: Set<String>,
        islandClassMap: Map<String, String>,
        matchableNames: Set<String>,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Any, Any>? {
        val islandInstanceMap = island.instances.associateBy { it.objectInstance.name }

        val anchorNames = findIslandAnchorNames(island.links, islandInstanceNames, matchableNames)
        val startAnchor = anchorNames.firstOrNull() ?: return null

        val orderedLinks = orderIslandLinksByBFS(island.links, startAnchor)
        val nodesNeedingBacktrackLabel = findNodesNeedingBacktrackLabel(orderedLinks, startAnchor)

        var chain: GraphTraversal<Any, Any> = AnonymousTraversal.`as`<Any>(
            VariableBinding.stepLabel(startAnchor)
        ) as GraphTraversal<Any, Any>

        var currentNode = startAnchor

        for ((link, isReversed) in orderedLinks) {
            val edgeLabel = EdgeLabelUtils.computeEdgeLabel(
                link.link.source.propertyName, link.link.target.propertyName
            )
            val fromNode = if (isReversed) link.link.target.objectName else link.link.source.objectName
            val toNode = if (isReversed) link.link.source.objectName else link.link.target.objectName

            if (fromNode != currentNode) {
                chain = chain.select<Any>(VariableBinding.stepLabel(fromNode)) as GraphTraversal<Any, Any>
            }

            chain = if (isReversed) {
                chain.`in`(edgeLabel) as GraphTraversal<Any, Any>
            } else {
                chain.out(edgeLabel) as GraphTraversal<Any, Any>
            }

            val targetClassName = islandClassMap[toNode]
            if (targetClassName != null) {
                chain = chain.hasLabel(targetClassName) as GraphTraversal<Any, Any>
            }

            val targetInstance = islandInstanceMap[toNode]
            if (targetInstance != null) {
                chain = applyPropertyEqualityConstraints(chain, targetInstance.objectInstance.className, targetInstance.objectInstance.properties, context, engine)
            }

            if (toNode in matchableNames || toNode in nodesNeedingBacktrackLabel) {
                chain = chain.`as`(VariableBinding.stepLabel(toNode)) as GraphTraversal<Any, Any>
            }

            currentNode = toNode
        }

        return chain
    }

    /**
     * Finds the anchor node names for an island — matched nodes that are connected to
     * island instances via island links but are not themselves island instances.
     *
     * @param links The island's links
     * @param islandInstanceNames Names of instances belonging to this island
     * @param matchableNames Names of matchable/delete instances in the main pattern
     * @return The set of anchor node names
     */
    private fun findIslandAnchorNames(
        links: List<TypedPatternLinkElement>,
        islandInstanceNames: Set<String>,
        matchableNames: Set<String>
    ): Set<String> {
        val anchorNames = mutableSetOf<String>()
        for (link in links) {
            val source = link.link.source.objectName
            val target = link.link.target.objectName
            if (source !in islandInstanceNames && source in matchableNames) anchorNames.add(source)
            if (target !in islandInstanceNames && target in matchableNames) anchorNames.add(target)
        }
        return anchorNames
    }

    /**
     * Orders island links into a BFS traversal sequence starting from [startAnchor].
     *
     * Returns a list of (link, isReversed) pairs. When [isReversed] is true the link
     * is traversed from target to source (i.e., using `.in(edgeLabel)` rather than `.out()`).
     *
     * @param links The island's links
     * @param startAnchor The node name to begin BFS from
     * @return Ordered list of links with traversal direction
     */
    private fun orderIslandLinksByBFS(
        links: List<TypedPatternLinkElement>,
        startAnchor: String
    ): List<Pair<TypedPatternLinkElement, Boolean>> {
        val visited = mutableSetOf(startAnchor)
        val orderedLinks = mutableListOf<Pair<TypedPatternLinkElement, Boolean>>()
        val remaining = links.toMutableList()

        var changed = true
        while (remaining.isNotEmpty() && changed) {
            changed = false
            val iterator = remaining.iterator()
            while (iterator.hasNext()) {
                val link = iterator.next()
                val source = link.link.source.objectName
                val target = link.link.target.objectName
                when {
                    source in visited -> {
                        orderedLinks.add(link to false)
                        visited.add(target)
                        iterator.remove()
                        changed = true
                    }
                    target in visited -> {
                        orderedLinks.add(link to true)
                        visited.add(source)
                        iterator.remove()
                        changed = true
                    }
                }
            }
        }

        return orderedLinks
    }

    /**
     * Determines which nodes in the ordered link sequence need a step label for
     * backtracking purposes.
     *
     * A node needs a backtrack label if it appears as the `from` node of any link where
     * it is not the current traversal head — i.e., the chain will need to `.select()`
     * back to it to continue exploring a different branch.
     *
     * @param orderedLinks The BFS-ordered list of links with direction flags
     * @param startAnchor The starting anchor node
     * @return Set of node names that require a step label
     */
    private fun findNodesNeedingBacktrackLabel(
        orderedLinks: List<Pair<TypedPatternLinkElement, Boolean>>,
        startAnchor: String
    ): Set<String> {
        val needed = mutableSetOf<String>()
        var current = startAnchor
        for ((link, isReversed) in orderedLinks) {
            val fromNode = if (isReversed) link.link.target.objectName else link.link.source.objectName
            val toNode = if (isReversed) link.link.source.objectName else link.link.target.objectName
            if (fromNode != current) needed.add(fromNode)
            current = toNode
        }
        return needed
    }

    /**
     * Applies all equality property constraints (== operator) from [properties] to [traversal].
     *
     * For constant values (ValueResult), applies `.has(graphKey, value)` inline.
     * For non-constant expressions, builds an equality traversal using [EqualityCompilerUtil].
     *
     * Used in island chain traversals and disconnected island constraints where the traversal
     * head is already positioned on the target vertex.
     *
     * @param traversal The traversal currently positioned on the target vertex.
     * @param className The metamodel class name of the vertex (for graph key resolution).
     * @param properties The property assignments to filter by.
     * @param context The transformation execution context.
     * @param engine The transformation engine.
     * @return The traversal extended with property constraint steps.
     */
    @Suppress("UNCHECKED_CAST")
    private fun applyPropertyEqualityConstraints(
        traversal: GraphTraversal<Any, Any>,
        className: String?,
        properties: List<TypedPatternPropertyAssignment>,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Any, Any> {
        var result = traversal
        for (property in properties) {
            if (property.operator != "==") continue
            val graphKey = engine.resolvePropertyGraphKey(className, property.propertyName)
            val compilationResult = compilePropertyExpression(property.value, context, engine, emptyList())
            if (compilationResult is CompilationResult.ValueResult) {
                result = result.has(graphKey, compilationResult.value) as GraphTraversal<Any, Any>
            } else if (compilationResult != null) {
                val propertyTraversal = AnonymousTraversal.values<Vertex, Any>(graphKey) as GraphTraversal<Any, Any>
                val expressionTraversal = compileExpressionToTraversal(
                    property.value, engine, context,
                    AnonymousTraversal.`as`<Any>(ANCHOR_LABEL)
                ) as GraphTraversal<Any, Any>
                val propertyType = resolveExpressionType(property.value, engine)
                    ?: throw IllegalStateException("Cannot resolve type for property expression: ${property.propertyName}")
                val equalityTraversal = EqualityCompilerUtil.buildEqualityTraversal(
                    "==",
                    propertyTraversal,
                    expressionTraversal,
                    propertyType,
                    propertyType,
                    engine.typeRegistry,
                    labelIdGenerator.getUniqueId(),
                    labelIdGenerator.getUniqueId()
                )
                result = result.filter(equalityTraversal.`is`(true)) as GraphTraversal<Any, Any>
            }
        }
        return result
    }

    /**
     * Adds a constraint for an island that has no links (fully disconnected).
     *
     * For each instance in the island, checks whether any vertex of the given class
     * exists in the graph:
     * - Forbid: `where(V().hasLabel(cls).count().is(eq(0)))` — no such vertex may exist
     * - Require: `where(V().hasLabel(cls).count().is(gt(0)))` — at least one must exist
     *
     * @param traversal The traversal to extend
     * @param island The disconnected island (instances only, no links)
     * @param isNegative True for forbid semantics, false for require
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @return The extended traversal with disconnected island constraints
     */
    @Suppress("UNCHECKED_CAST")
    private fun addDisconnectedIslandConstraint(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        island: Island,
        isNegative: Boolean,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal
        for (instance in island.instances) {
            val className = instance.objectInstance.className ?: continue
            val countPredicate = if (isNegative) P.eq(0L) else P.gt(0L)
            var clause: GraphTraversal<Any, Any> = AnonymousTraversal.V<Any>()
                .hasLabel(className) as GraphTraversal<Any, Any>
            clause = applyPropertyEqualityConstraints(clause, instance.objectInstance.className, instance.objectInstance.properties, context, engine)
            result = result.where(clause.count().`is`(countPredicate)) as GraphTraversal<Vertex, Map<String, Any>>
        }
        return result
    }

    /**
     * Adds where clause constraints using traversal-based expression compilation.
     *
     * Where clauses are compiled to traversals and applied as where() filters.
     * For boolean expressions, the compiled traversal determines if the where
     * clause passes or fails.
     *
     * @param traversal The traversal to extend with where clause constraints
     * @param whereClauses List of where clause elements to apply
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @return The extended traversal with all where clause constraints added
     */
    @Suppress("UNCHECKED_CAST")
    private fun addWhereClauseConstraints(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        whereClauses: List<TypedPatternWhereClauseElement>,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (whereClause in whereClauses) {
            val compiledTraversal = compileExpressionToTraversal(whereClause.whereClause.expression, engine, context)
            result = result.where(compiledTraversal.`is`(true)) as GraphTraversal<Vertex, Map<String, Any>>
        }

        return result
    }

    /**
     * Adds property comparison constraints as where() filters for non-constant property values.
     *
     * Handles property constraints (== operator) that cannot be inlined into the match()
     * clause. Specifically covers:
     * - No-class instances with a constant comparison value (cannot use match-clause .has())
     * - Any instance with a non-constant (expression) comparison value
     *
     * @param traversal The main traversal to extend
     * @param instances The instances with property constraints to check
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @return The extended traversal with property where constraints
     */
    @Suppress("UNCHECKED_CAST")
    private fun addPropertyWhereConstraints(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        instances: List<TypedPatternObjectInstanceElement>,
        context: TransformationExecutionContext,
        engine: TransformationEngine
    ): GraphTraversal<Vertex, Map<String, Any>> {
        var result = traversal

        for (instance in instances) {
            val instanceName = instance.objectInstance.name
            val instanceLabel = VariableBinding.stepLabel(instanceName)
            val className = instance.objectInstance.className

            for (property in instance.objectInstance.properties) {
                if (property.operator == "==") {
                    val compilationResult = compilePropertyExpression(property.value, context, engine, emptyList())
                    val graphKey = engine.resolvePropertyGraphKey(className, property.propertyName)

                    if (className == null && compilationResult is CompilationResult.ValueResult) {
                        result = result.where(
                            AnonymousTraversal.select<Any, Any>(instanceLabel)
                                .has(graphKey, compilationResult.value)
                        ) as GraphTraversal<Vertex, Map<String, Any>>
                    } else if (compilationResult != null && compilationResult !is CompilationResult.ValueResult) {
                        val propertyTraversal = AnonymousTraversal.select<Any, Any>(instanceLabel)
                            .values<Any>(graphKey) as GraphTraversal<Any, Any>

                        val expressionTraversal = compileExpressionToTraversal(
                            property.value,
                            engine,
                            context,
                            AnonymousTraversal.`as`<Any>(ANCHOR_LABEL)
                        ) as GraphTraversal<Any, Any>

                        val propertyType = resolveExpressionType(property.value, engine)
                            ?: throw IllegalStateException("Cannot resolve type for property expression: ${property.propertyName}")

                        val equalityTraversal = EqualityCompilerUtil.buildEqualityTraversal(
                            "==",
                            propertyTraversal,
                            expressionTraversal,
                            propertyType,
                            propertyType,
                            engine.typeRegistry,
                            labelIdGenerator.getUniqueId(),
                            labelIdGenerator.getUniqueId()
                        )

                        result = result.where(equalityTraversal.`is`(true))
                            as GraphTraversal<Vertex, Map<String, Any>>
                    }
                }
            }
        }

        return result
    }

    /**
     * Compiles an expression to a GraphTraversal using the expression compiler registry.
     *
     * @param expression The expression to compile
     * @param engine The transformation engine with compiler registry
     * @param context The transformation execution context
     * @param initialTraversal Optional initial traversal to start from
     * @return The compiled traversal
     * @throws IllegalStateException if the expression type is not supported
     */
    private fun compileExpressionToTraversal(
        expression: TypedExpression,
        engine: TransformationEngine,
        context: TransformationExecutionContext,
        initialTraversal: GraphTraversal<*, *>? = null
    ): GraphTraversal<*, *> {
        if (!engine.expressionCompilerRegistry.canCompile(expression)) {
            throw IllegalStateException(
                "Cannot compile expression to traversal. " +
                "Expression type: ${expression.javaClass.simpleName} is not supported."
            )
        }

        return engine.expressionCompilerRegistry.compile(
            expression,
            newCompilationContext(engine, context),
            initialTraversal
        ).traversal
    }

    /**
     * Compiles a property value expression and returns only the resolved value.
     *
     * For constant (ValueResult) expressions, returns the value directly. For
     * traversal-based expressions, executes the traversal and returns the first result.
     *
     * @param expression The expression to compile
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances available for reference
     * @return The resolved value, or null if compilation fails or produces no result
     */
    @Suppress("UNCHECKED_CAST")
    private fun getPropertyValue(
        expression: TypedExpression,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>
    ): Any? {
        val result = compilePropertyExpression(expression, context, engine, matchedInstanceNames)
        if (result == null) return null

        if (result is CompilationResult.ValueResult) {
            return result.value
        }

        val traversal = result.traversal as GraphTraversal<Any, Any>
        val injectedTraversal = engine.traversalSource.inject(null as Any?).flatMap(traversal)
        return if (injectedTraversal.hasNext()) injectedTraversal.next() else null
    }

    /**
     * Compiles a property value expression and returns the full compilation result.
     *
     * This variant returns the [CompilationResult], allowing the caller to distinguish
     * between constant and non-constant (traversal) results.
     *
     * @param expression The expression to compile
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances available for reference
     * @return The compilation result, or null if compilation fails
     * @throws IllegalStateException if no compiler is registered for the expression type
     */
    private fun compilePropertyExpression(
        expression: TypedExpression,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>
    ): CompilationResult? {
        if (!engine.expressionCompilerRegistry.canCompile(expression)) {
            throw IllegalStateException(
                "Expression compiler not found for expression of type '${expression::class.simpleName}'. " +
                "Ensure a compiler is registered for this expression kind."
            )
        }

        return try {
            engine.expressionCompilerRegistry.compile(expression, newCompilationContext(engine, context))
        } catch (e: Exception) {
            throw IllegalStateException(
                "Failed to compile expression '${expression::class.simpleName}': ${e.message}. " +
                "This may indicate a missing type registration for metamodel types.",
                e
            )
        }
    }

    /**
     * Creates a new [CompilationContext] backed by the shared [labelIdGenerator].
     *
     * @param engine Provides type information, traversal source and type registry
     * @param context Provides the current variable scope
     * @return A new compilation context sharing this executor's label counter
     */
    private fun newCompilationContext(
        engine: TransformationEngine,
        context: TransformationExecutionContext
    ): CompilationContext = CompilationContext(
        types = engine.types,
        currentScope = context.variableScope,
        traversalSource = engine.traversalSource,
        typeRegistry = engine.typeRegistry,
        idGenerator = labelIdGenerator
    )

    /**
     * Resolves the type of an expression from the engine's type array.
     *
     * @param expression The expression to get the type for
     * @param engine The transformation engine containing type information
     * @return The ValueType of the expression, or null if not available
     */
    private fun resolveExpressionType(
        expression: TypedExpression,
        engine: TransformationEngine
    ): com.mdeo.expression.ast.types.ValueType? {
        val typeIndex = expression.evalType
        if (typeIndex < 0 || typeIndex >= engine.types.size) return null
        val type = engine.types[typeIndex]
        return type as? com.mdeo.expression.ast.types.ValueType
    }

    /**
     * Returns true if [type] is a collection type (list or set cardinality).
     *
     * @param type The type to check (nullable)
     * @param engine The transformation engine with type registry
     * @return true if the type has list or set cardinality
     */
    private fun isCollectionType(
        type: com.mdeo.expression.ast.types.ValueType?,
        engine: TransformationEngine
    ): Boolean {
        if (type == null) return false
        if (type !is com.mdeo.expression.ast.types.ClassTypeRef) return false
        val typeDefinition = engine.typeRegistry.getType(type)!!
        val registryCardinality = typeDefinition.cardinality
        return registryCardinality == VertexProperty.Cardinality.list || registryCardinality == VertexProperty.Cardinality.set
    }

    /**
     * Adds the select() step for extracting named bindings.
     *
     * Uses step labels for selecting matched instances and variable labels for variables.
     * When selecting a single element, returns that element directly.
     * When selecting multiple, returns a map with step labels as keys.
     *
     * @param traversal The traversal to extend with the select step
     * @param instanceNames List of instance names (will be converted to step labels)
     * @param variableLabels List of variable labels (already in label form, used as-is)
     * @return The extended traversal with select step for extracting named bindings
     */
    @Suppress("UNCHECKED_CAST")
    private fun addSelectStep(
        traversal: GraphTraversal<Vertex, Map<String, Any>>,
        instanceNames: List<String>,
        variableLabels: List<String> = emptyList()
    ): GraphTraversal<Vertex, Any> {
        val instanceStepLabels = instanceNames.map { VariableBinding.stepLabel(it) }
        val allLabels = instanceStepLabels + variableLabels

        return when (allLabels.size) {
            0 -> traversal as GraphTraversal<Vertex, Any>
            1 -> traversal.select<Any>(allLabels[0]) as GraphTraversal<Vertex, Any>
            else -> traversal.select<Any>(
                allLabels[0], allLabels[1], *allLabels.drop(2).toTypedArray()
            ) as GraphTraversal<Vertex, Any>
        }
    }

    /**
     * Executes the traversal and extracts match results.
     *
     * Converts step labels back to original instance names and handles the fact that
     * select() with one element returns the element directly, while select() with
     * multiple elements returns a map.
     *
     * @param traversal The unified traversal to execute
     * @param elements Categorized pattern elements for result extraction
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances (for classification)
     * @return List of matched results with classified nodes and bindings
     */
    @Suppress("UNCHECKED_CAST")
    private fun executeTraversalAndExtract(
        traversal: GraphTraversal<Vertex, Any>,
        elements: PatternCategories,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>
    ): List<MatchResult.Matched> {
        val instanceNames = elements.allInstanceNames
        val variableLabels = elements.variables.map { VariableBinding.variableLabel(it.variable.name) }
        val allLabels = instanceNames + variableLabels

        return traversal.toList().map { rawResult ->
            val result: Map<String, Any> = when {
                allLabels.isEmpty() -> {
                    rawResult as Map<String, Any>
                }
                allLabels.size == 1 -> {
                    val label = allLabels[0]
                    mapOf(label to rawResult)
                }
                else -> {
                    val rawMap = rawResult as Map<String, Any>
                    val instanceMap = instanceNames.associateWith { name ->
                        rawMap[VariableBinding.stepLabel(name)]!!
                    }
                    val variableMap = variableLabels.associateWith { label ->
                        rawMap[label]!!
                    }
                    instanceMap + variableMap
                }
            }
            extractMatchResult(result, elements, context, engine, matchedInstanceNames)
        }
    }

    /**
     * Extracts a [MatchResult.Matched] from a raw traversal result map.
     *
     * Variables are read from the result map, and their scope binding is updated
     * from [VariableBinding.LabelBinding] to [VariableBinding.ValueBinding] for use
     * in subsequent operations. Instance results are classified as matched, created,
     * or deleted.
     *
     * @param result The raw result map from traversal execution (names to values)
     * @param elements Categorized pattern elements
     * @param context The transformation execution context
     * @param engine The transformation engine
     * @param matchedInstanceNames Names of matched instances for node classification
     * @return A MatchResult.Matched with bindings and classified node IDs
     */
    private fun extractMatchResult(
        result: Map<String, Any>,
        elements: PatternCategories,
        context: TransformationExecutionContext,
        engine: TransformationEngine,
        matchedInstanceNames: List<String>
    ): MatchResult.Matched {
        val bindings = mutableMapOf<String, Any?>()
        for (variableElement in elements.variables) {
            val variableName = variableElement.variable.name
            val variableLabel = VariableBinding.variableLabel(variableName)
            val value = result[variableLabel]
            bindings[variableName] = value

            context.variableScope.setBinding(variableName, VariableBinding.ValueBinding(value))
        }

        val instanceMappings = mutableMapOf<String, VertexRef>()
        val matchedNodeIds = mutableSetOf<Any>()
        val createdNodeIds = mutableSetOf<Any>()
        val deletedNodeIds = mutableSetOf<Any>()

        val createInstanceNames = elements.createInstances.map { it.objectInstance.name }.toSet()
        val deleteInstanceNames = elements.deleteInstances.map { it.objectInstance.name }.toSet()

        for (name in elements.allInstanceNames) {
            classifyNodeByName(
                name, result[name], createInstanceNames, deleteInstanceNames,
                instanceMappings, matchedNodeIds, createdNodeIds, deletedNodeIds, engine
            )
        }

        return MatchResult.Matched(bindings, instanceMappings, matchedNodeIds, createdNodeIds, deletedNodeIds)
    }

    /**
     * Classifies a single node into the matched, created, or deleted category.
     *
     * Also registers created nodes with the instance name registry for lookup by name.
     *
     * @param name The instance name
     * @param value The vertex or value from the traversal result
     * @param createInstanceNames Set of instance names marked for creation
     * @param deleteInstanceNames Set of instance names marked for deletion
     * @param instanceMappings Mutable map to populate with name-to-VertexRef mappings
     * @param matchedNodeIds Mutable set to add matched node IDs to
     * @param createdNodeIds Mutable set to add created node IDs to
     * @param deletedNodeIds Mutable set to add deleted node IDs to
     * @param engine The transformation engine for instance name registration
     */
    private fun classifyNodeByName(
        name: String,
        value: Any?,
        createInstanceNames: Set<String>,
        deleteInstanceNames: Set<String>,
        instanceMappings: MutableMap<String, VertexRef>,
        matchedNodeIds: MutableSet<Any>,
        createdNodeIds: MutableSet<Any>,
        deletedNodeIds: MutableSet<Any>,
        engine: TransformationEngine
    ) {
        if (value is Vertex) {
            val rawId = value.id()
            val vertexRef = engine.modelGraph.createVertexRef(rawId)
            instanceMappings[name] = vertexRef
            when {
                createInstanceNames.contains(name) -> {
                    createdNodeIds.add(rawId)
                    engine.instanceNameRegistry.registerWithUniqueName(rawId, name)
                }
                deleteInstanceNames.contains(name) -> {
                    matchedNodeIds.add(rawId)
                    deletedNodeIds.add(rawId)
                }
                else -> matchedNodeIds.add(rawId)
            }
        }
    }

    /**
     * Result of building match clauses.
     *
     * Contains both the match clause traversals and the compiled variable expressions.
     *
     * @property clauses The array of match clause traversals
     * @property compiledVariables The compiled variable expressions indexed by variable label
     */
    private data class MatchClauseBuildResult(
        val clauses: Array<GraphTraversal<Any, Any>>,
        val compiledVariables: CompiledVariables
    ) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (javaClass != other?.javaClass) return false
            other as MatchClauseBuildResult
            if (!clauses.contentEquals(other.clauses)) return false
            if (compiledVariables != other.compiledVariables) return false
            return true
        }

        override fun hashCode(): Int {
            var result = clauses.contentHashCode()
            result = 31 * result + compiledVariables.hashCode()
            return result
        }
    }
}
