server {
    listen 80;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Metamodel plugin 
    location ^~ /plugin/metamodel/ {
        proxy_pass ${PLUGIN_METAMODEL_SERVICE}/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Model plugin
    location ^~ /plugin/model/ {
        proxy_pass ${PLUGIN_MODEL_SERVICE}/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy API requests to backend
    location ^~ /api/ {
        proxy_pass ${BACKEND_SERVICE};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Pass cookies
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
        
        # Pass CSRF header
        proxy_set_header X-CSRF-Token $http_x_csrf_token;
        proxy_pass_header X-CSRF-Token;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Non-html files
    location ~* \.(?!html$)[a-zA-Z0-9]+$ {
        root   /usr/share/nginx/html;
        try_files $uri =404;
    }

    # Html files
    location / {
        root   /usr/share/nginx/html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires 0;
        try_files $uri $uri/ /index.html;
    }
}
