package com.mdeo.script.compiler

/**
 * Represents a compiled script program.
 * Contains the generated bytecode for all files.
 *
 * @param classes Map of file URI to the compiled bytecode for that file.
 *                Each file is compiled into a separate JVM class.
 * @param generatedInterfaces Map of interface name to bytecode for generated functional interfaces.
 *                            These are custom interfaces generated for lambdas (e.g., Lambda$Int$Int).
 */
data class CompiledProgram(
    val classes: Map<String, CompiledClass>,
    val generatedInterfaces: Map<String, ByteArray> = emptyMap()
)

/**
 * Represents a compiled class for a single script file.
 *
 * @param fileUri The file URI this class was compiled from.
 * @param className The internal JVM class name (e.g., "com/example/Script$file").
 * @param bytecode The compiled bytecode for this class.
 */
data class CompiledClass(
    val fileUri: String,
    val className: String,
    val bytecode: ByteArray
) {
    /**
     * Checks equality with another object.
     * Two CompiledClass instances are equal if they have the same fileUri, className,
     * and bytecode content.
     *
     * @param other The object to compare with this instance.
     * @return True if the other object is a CompiledClass with identical fileUri, className,
     *         and bytecode content; false otherwise.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other !is CompiledClass) {
            return false
        }
        return fileUri == other.fileUri && 
               className == other.className && 
               bytecode.contentEquals(other.bytecode)
    }

    /**
     * Computes the hash code for this CompiledClass.
     * The hash code is computed from fileUri, className, and bytecode content.
     *
     * @return The hash code value for this object.
     */
    override fun hashCode(): Int {
        var result = fileUri.hashCode()
        result = 31 * result + className.hashCode()
        result = 31 * result + bytecode.contentHashCode()
        return result
    }
}
