package com.mdeo.script.compiler

import com.mdeo.script.ast.TypedAst
import com.mdeo.script.ast.TypedFunction
import com.mdeo.expression.ast.types.ClassTypeRef
import com.mdeo.expression.ast.types.ReturnType
import com.mdeo.expression.ast.types.VoidType
import com.mdeo.script.compiler.expressions.AssertNonNullCompiler
import com.mdeo.script.compiler.expressions.BinaryExpressionCompiler
import com.mdeo.script.compiler.expressions.BooleanLiteralCompiler
import com.mdeo.script.compiler.expressions.DoubleLiteralCompiler
import com.mdeo.script.compiler.expressions.ExpressionCallCompiler
import com.mdeo.script.compiler.expressions.FloatLiteralCompiler
import com.mdeo.script.compiler.expressions.IdentifierCompiler
import com.mdeo.script.compiler.expressions.IntLiteralCompiler
import com.mdeo.script.compiler.expressions.LambdaCompiler
import com.mdeo.script.compiler.expressions.LongLiteralCompiler
import com.mdeo.script.compiler.expressions.NullLiteralCompiler
import com.mdeo.script.compiler.expressions.FunctionCallCompiler
import com.mdeo.script.compiler.expressions.MemberAccessCompiler
import com.mdeo.script.compiler.expressions.MemberCallCompiler
import com.mdeo.script.compiler.expressions.StringLiteralCompiler
import com.mdeo.script.compiler.expressions.TernaryExpressionCompiler
import com.mdeo.script.compiler.expressions.TypeCastCompiler
import com.mdeo.script.compiler.expressions.TypeCheckCompiler
import com.mdeo.script.compiler.expressions.UnaryExpressionCompiler
import com.mdeo.script.compiler.registry.function.FileFunctionRegistry
import com.mdeo.script.compiler.registry.function.FunctionRegistry
import com.mdeo.script.compiler.registry.function.GlobalFunctionRegistry
import com.mdeo.script.compiler.statements.AssignmentCompiler
import com.mdeo.script.compiler.statements.BreakStatementCompiler
import com.mdeo.script.compiler.statements.ContinueStatementCompiler
import com.mdeo.script.compiler.statements.ExpressionStatementCompiler
import com.mdeo.script.compiler.statements.ForStatementCompiler
import com.mdeo.script.compiler.statements.IfStatementCompiler
import com.mdeo.script.compiler.statements.ReturnStatementCompiler
import com.mdeo.script.compiler.statements.VariableDeclarationCompiler
import com.mdeo.script.compiler.statements.WhileStatementCompiler
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Main compiler for the script language.
 * 
 * Takes a CompilationInput containing TypedASTs for each file and
 * generates JVM bytecode for each file. Each file is compiled into
 * a separate JVM class containing static methods for each function.
 */
class ScriptCompiler {

    /**
     * The registered expression compilers.
     */
    private val expressionCompilers: List<ExpressionCompiler> = listOf(
        IntLiteralCompiler(),
        LongLiteralCompiler(),
        FloatLiteralCompiler(),
        DoubleLiteralCompiler(),
        BooleanLiteralCompiler(),
        StringLiteralCompiler(),
        NullLiteralCompiler(),
        BinaryExpressionCompiler(),
        UnaryExpressionCompiler(),
        TernaryExpressionCompiler(),
        IdentifierCompiler(),
        MemberAccessCompiler(),
        FunctionCallCompiler(),
        MemberCallCompiler(),
        ExpressionCallCompiler(),
        LambdaCompiler(),
        AssertNonNullCompiler(),
        TypeCastCompiler(),
        TypeCheckCompiler()
    )

    /**
     * The registered statement compilers.
     */
    private val statementCompilers: List<StatementCompiler> = listOf(
        ReturnStatementCompiler(),
        VariableDeclarationCompiler(),
        AssignmentCompiler(),
        WhileStatementCompiler(),
        ForStatementCompiler(),
        IfStatementCompiler(),
        BreakStatementCompiler(),
        ContinueStatementCompiler(),
        ExpressionStatementCompiler()
    )

    /**
     * Compiles the given input to a CompiledProgram.
     *
     * Creates hierarchical function registries for each file to properly handle
     * cross-file imports before compiling.
     * 
     * @param input The compilation input containing TypedASTs for each file.
     * @return A CompiledProgram containing the generated bytecode.
     */
    fun compile(input: CompilationInput): CompiledProgram {
        val allClasses = mutableMapOf<String, CompiledClass>()
        val allInterfaces = mutableMapOf<String, ByteArray>()

        val fileRegistries = FileFunctionRegistry.createForCompilation(
            input.files,
            GlobalFunctionRegistry.GLOBAL,
            ::fileUriToClassName
        )

        for ((fileUri, ast) in input.files) {
            val className = fileUriToClassName(fileUri)
            val generatedInterfaces = mutableMapOf<String, ByteArray>()
            val functionRegistry = fileRegistries[fileUri] ?: GlobalFunctionRegistry.GLOBAL
            val bytecode = compileFile(fileUri, ast, className, generatedInterfaces, functionRegistry)

            allClasses[fileUri] = CompiledClass(fileUri, className, bytecode)

            allInterfaces.putAll(generatedInterfaces)
        }

        return CompiledProgram(allClasses, allInterfaces)
    }

    /**
     * Converts a file URI to a JVM internal class name.
     * Uses hex encoding for non-alphanumeric characters to ensure uniqueness.
     * 
     * @param fileUri The file URI.
     * @return The JVM internal class name.
     */
    private fun fileUriToClassName(fileUri: String): String {
        val sanitized = buildString {
            for (char in fileUri) {
                when {
                    char.isLetterOrDigit() -> append(char)
                    else -> append("_${char.code.toString(16).uppercase().padStart(2, '0')}")
                }
            }
        }
        return "com/mdeo/script/generated/Script_$sanitized"
    }

    /**
     * Compiles a single file to bytecode.
     * 
     * @param fileUri The file URI.
     * @param ast The TypedAST for the file.
     * @param className The JVM internal class name.
     * @param generatedInterfaces Shared map for collecting generated functional interfaces.
     * @param functionRegistry The function registry for resolving file-scope and imported functions.
     * @return The compiled bytecode.
     */
    private fun compileFile(
        fileUri: String,
        ast: TypedAst,
        className: String,
        generatedInterfaces: MutableMap<String, ByteArray>,
        functionRegistry: FunctionRegistry
    ): ByteArray {
        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)

        cw.visit(
            Opcodes.V11,
            Opcodes.ACC_PUBLIC,
            className,
            null,
            "java/lang/Object",
            null
        )

        cw.visitSource(fileUri, null)

        for (function in ast.functions) {
            compileFunction(function, ast, className, cw, generatedInterfaces, functionRegistry)
        }

        cw.visitEnd()

        return cw.toByteArray()
    }

    /**
     * Compiles a function to a static method.
     * 
     * @param function The function to compile.
     * @param ast The TypedAST containing type information.
     * @param className The JVM internal class name.
     * @param cw The ClassWriter to emit bytecode to.
     * @param lambdaContext The context for tracking lambda method names.
     * @param generatedInterfaces Shared map for collecting generated functional interfaces.
     * @param functionRegistry The function registry for resolving function references.
     */
    private fun compileFunction(
        function: TypedFunction,
        ast: TypedAst,
        className: String,
        cw: ClassWriter,
        generatedInterfaces: MutableMap<String, ByteArray>,
        functionRegistry: FunctionRegistry
    ) {
        val returnType = ast.types[function.returnType]
        val descriptor = functionRegistry.lookupFunction(function.name)!!.getOverload("")!!.descriptor

        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC,
            function.name,
            descriptor,
            null,
            null
        )

        val paramsScope = Scope(level = 2)

        for (param in function.parameters) {
            val paramType = ast.types[param.type]
            paramsScope.declareVariable(param.name, paramType)
        }

        val tempContext = CompilationContext(
            ast, className, expressionCompilers, statementCompilers, function.returnType,
            paramsScope, classWriter = cw, generatedInterfaces = generatedInterfaces,
            functionRegistry = functionRegistry
        )

        val scopeBuilder = ScopeBuilder(tempContext)
        val bodyScope = scopeBuilder.buildFunctionScope(function, paramsScope)

        val indexAssigner = LocalVariableIndexAssigner(tempContext)
        indexAssigner.assignIndices(paramsScope, isStatic = true)

        val context = CompilationContext(
            ast, className, expressionCompilers, statementCompilers, function.returnType,
            paramsScope, scopeBuilder.statementScopes, classWriter = cw,
            generatedInterfaces = generatedInterfaces, functionRegistry = functionRegistry
        )
        context.enterScope(bodyScope)

        mv.visitCode()

        for (statement in function.body.body) {
            context.compileStatement(statement, mv)
        }

        ensureReturn(returnType, mv)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Ensures the method ends with a return instruction.
     * This adds a return instruction if the method body doesn't end with one.
     * 
     * @param returnType The return type of the method.
     * @param mv The method visitor.
     */
    private fun ensureReturn(returnType: ReturnType, mv: MethodVisitor) {
        if (returnType is VoidType) {
            mv.visitInsn(Opcodes.RETURN)
        }
    }
}
