package com.mdeo.script.compiler

import com.mdeo.expression.ast.types.MetamodelData
import com.mdeo.script.ast.TypedAst
import com.mdeo.script.ast.TypedFunction
import com.mdeo.expression.ast.types.ClassTypeRef
import com.mdeo.expression.ast.types.ReturnType
import com.mdeo.expression.ast.types.VoidType
import com.mdeo.script.compiler.expressions.AssertNonNullCompiler
import com.mdeo.script.compiler.expressions.BinaryExpressionCompiler
import com.mdeo.script.compiler.expressions.BooleanLiteralCompiler
import com.mdeo.script.compiler.expressions.DoubleLiteralCompiler
import com.mdeo.script.compiler.expressions.ExpressionCallCompiler
import com.mdeo.script.compiler.expressions.FloatLiteralCompiler
import com.mdeo.script.compiler.expressions.IdentifierCompiler
import com.mdeo.script.compiler.expressions.IntLiteralCompiler
import com.mdeo.script.compiler.expressions.LambdaCompiler
import com.mdeo.script.compiler.expressions.LongLiteralCompiler
import com.mdeo.script.compiler.expressions.NullLiteralCompiler
import com.mdeo.script.compiler.expressions.FunctionCallCompiler
import com.mdeo.script.compiler.expressions.MemberAccessCompiler
import com.mdeo.script.compiler.expressions.MemberCallCompiler
import com.mdeo.script.compiler.expressions.StringLiteralCompiler
import com.mdeo.script.compiler.expressions.TernaryExpressionCompiler
import com.mdeo.script.compiler.expressions.TypeCastCompiler
import com.mdeo.script.compiler.expressions.TypeCheckCompiler
import com.mdeo.script.compiler.expressions.UnaryExpressionCompiler
import com.mdeo.script.compiler.expressions.ListLiteralCompiler
import com.mdeo.script.compiler.model.ScriptClassBytecodeGenerator
import com.mdeo.script.compiler.model.ScriptEnumBytecodeGenerator
import com.mdeo.script.compiler.model.ScriptMetamodelTypeRegistrar
import com.mdeo.script.compiler.util.toJvmBinaryName
import com.mdeo.script.compiler.registry.function.FileFunctionRegistry
import com.mdeo.script.compiler.registry.function.FunctionRegistry
import com.mdeo.script.compiler.registry.function.GlobalFunctionRegistry
import com.mdeo.script.compiler.registry.property.GlobalPropertyRegistry
import com.mdeo.script.compiler.registry.type.TypeRegistry
import com.mdeo.script.compiler.statements.AssignmentCompiler
import com.mdeo.script.compiler.statements.BreakStatementCompiler
import com.mdeo.script.compiler.statements.ContinueStatementCompiler
import com.mdeo.script.compiler.statements.ExpressionStatementCompiler
import com.mdeo.script.compiler.statements.ForStatementCompiler
import com.mdeo.script.compiler.statements.IfStatementCompiler
import com.mdeo.script.compiler.statements.ReturnStatementCompiler
import com.mdeo.script.compiler.statements.VariableDeclarationCompiler
import com.mdeo.script.compiler.statements.WhileStatementCompiler
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Main compiler for the script language.
 *
 * Takes a [CompilationInput] containing [TypedAst]s for each file and generates JVM bytecode
 * for each file.  Each file is compiled into a separate JVM class containing static methods
 * for each function.
 */
class ScriptCompiler {

    /**
     * The registered expression compilers.
     */
    private val expressionCompilers: List<ExpressionCompiler> = listOf(
        IntLiteralCompiler(),
        LongLiteralCompiler(),
        FloatLiteralCompiler(),
        DoubleLiteralCompiler(),
        BooleanLiteralCompiler(),
        StringLiteralCompiler(),
        NullLiteralCompiler(),
        BinaryExpressionCompiler(),
        UnaryExpressionCompiler(),
        TernaryExpressionCompiler(),
        IdentifierCompiler(),
        MemberAccessCompiler(),
        FunctionCallCompiler(),
        MemberCallCompiler(),
        ExpressionCallCompiler(),
        LambdaCompiler(),
        AssertNonNullCompiler(),
        TypeCastCompiler(),
        TypeCheckCompiler(),
        ListLiteralCompiler()
    )

    /**
     * The registered statement compilers.
     */
    private val statementCompilers: List<StatementCompiler> = listOf(
        ReturnStatementCompiler(),
        VariableDeclarationCompiler(),
        AssignmentCompiler(),
        WhileStatementCompiler(),
        ForStatementCompiler(),
        IfStatementCompiler(),
        BreakStatementCompiler(),
        ContinueStatementCompiler(),
        ExpressionStatementCompiler()
    )

    /**
     * Compiles the given input to a [CompiledProgram].
     *
     * Creates hierarchical function registries for each file to properly handle
     * cross-file imports before compiling.
     *
     * @param input The compilation input containing [TypedAst]s for each file.
     * @return A [CompiledProgram] containing the generated bytecode.
     */
    fun compile(input: CompilationInput): CompiledProgram {
        return compile(input, metamodelData = null)
    }

    /**
     * Compiles the given input with optional metamodel support.
     *
     * When [metamodelData] is provided, generates bytecode for:
     * - Enum value classes and enum container classes
     * - [ModelInstance][com.mdeo.script.runtime.model.ModelInstance] subclasses for each
     *   metamodel class
     * - A [TypeRegistry] enriched with metamodel types
     *
     * The metamodel path is taken directly from [metamodelData.path][MetamodelData.path].
     *
     * @param input The compilation input containing [TypedAst]s for each file.
     * @param metamodelData Optional metamodel data for type-safe model access. Must have a
     *   non-blank [MetamodelData.path] when provided.
     * @return A [CompiledProgram] containing the generated bytecode.
     */
    fun compile(
        input: CompilationInput,
        metamodelData: MetamodelData?
    ): CompiledProgram {
        val allBytecodes = mutableMapOf<String, ByteArray>()
        val instanceClassNames = mutableMapOf<String, String>()
        val enumContainerClassNames = mutableMapOf<String, String>()

        val typeRegistries = if (metamodelData != null && metamodelData.path.isNotBlank()) {
            generateMetamodelBytecodes(metamodelData, allBytecodes, instanceClassNames, enumContainerClassNames)
            createTypeRegistries(metamodelData, metamodelData.path)
        } else {
            TypeRegistries(TypeRegistry.GLOBAL, GlobalPropertyRegistry())
        }

        val fileRegistries = FileFunctionRegistry.createForCompilation(
            input.files,
            GlobalFunctionRegistry.GLOBAL,
            ::filePathToClassName
        )

        val (scriptFileBytecodes, scriptFileToClass) = compileAllFiles(
            input, fileRegistries, typeRegistries
        )
        allBytecodes.putAll(scriptFileBytecodes)

        return CompiledProgram(allBytecodes, scriptFileToClass, instanceClassNames, enumContainerClassNames)
    }

    /**
     * Generates JVM bytecode for all metamodel types (enums and classes) and adds the results
     * to [allBytecodes].  Also populates [instanceClassNames] and [enumContainerClassNames]
     * with the binary class names of the generated types.
     */
    private fun generateMetamodelBytecodes(
        metamodelData: MetamodelData,
        allBytecodes: MutableMap<String, ByteArray>,
        instanceClassNames: MutableMap<String, String>,
        enumContainerClassNames: MutableMap<String, String>
    ) {
        val enumResult = ScriptEnumBytecodeGenerator.generateEnumBytecodes(metamodelData)
        enumResult.allBytecodes().forEach { (internalName, bytecode) ->
            allBytecodes[internalName.toJvmBinaryName()] = bytecode
        }
        for (enumData in metamodelData.enums) {
            enumContainerClassNames[enumData.name] =
                ScriptEnumBytecodeGenerator.getEnumContainerClassName(enumData.name).toJvmBinaryName()
        }

        val classResult = ScriptClassBytecodeGenerator.generateClassBytecodes(metamodelData)
        classResult.classBytecodes.forEach { (internalName, bytecode) ->
            allBytecodes[internalName.toJvmBinaryName()] = bytecode
        }
        classResult.containerBytecodes.forEach { (internalName, bytecode) ->
            allBytecodes[internalName.toJvmBinaryName()] = bytecode
        }
        for (classData in metamodelData.classes) {
            instanceClassNames[classData.name] =
                ScriptClassBytecodeGenerator.getInstanceClassName(classData.name).toJvmBinaryName()
        }
    }

    /**
     * Creates a [TypeRegistries] bundle from the given metamodel.
     *
     * @param metamodelData The metamodel data.
     * @param metamodelPath The absolute path to the metamodel file.
     * @return The [TypeRegistries] for use during script compilation.
     */
    private fun createTypeRegistries(metamodelData: MetamodelData, metamodelPath: String): TypeRegistries {
        val compilationResult = ScriptMetamodelTypeRegistrar.createRegistry(metamodelData, metamodelPath)
        return TypeRegistries(compilationResult.typeRegistry, compilationResult.fileScopeRegistry)
    }

    /**
     * Compiles all script files from [input] and returns a pair of:
     * - a map of binary class name → bytecode for the generated script classes (and any
     *   functional interfaces they require), and
     * - a map of file path → binary class name.
     */
    private fun compileAllFiles(
        input: CompilationInput,
        fileRegistries: Map<String, FileFunctionRegistry>,
        typeRegistries: TypeRegistries
    ): Pair<Map<String, ByteArray>, Map<String, String>> {
        val allBytecodes = mutableMapOf<String, ByteArray>()
        val scriptFileToClass = mutableMapOf<String, String>()

        for ((filePath, ast) in input.files) {
            val internalName = filePathToClassName(filePath)
            val binaryName = internalName.toJvmBinaryName()
            val generatedInterfaces = mutableMapOf<String, ByteArray>()
            val functionRegistry = fileRegistries[filePath] ?: GlobalFunctionRegistry.GLOBAL

            val bytecode = compileFile(
                filePath, ast, internalName, generatedInterfaces,
                functionRegistry, typeRegistries.typeRegistry, typeRegistries.fileScopePropertyRegistry
            )

            allBytecodes[binaryName] = bytecode
            scriptFileToClass[filePath] = binaryName

            generatedInterfaces.forEach { (internalIface, ifaceBytecode) ->
                allBytecodes[internalIface.toJvmBinaryName()] = ifaceBytecode
            }
        }

        return allBytecodes to scriptFileToClass
    }

    /**
     * Converts a file path to a JVM internal class name.
     *
     * Uses hex encoding for non-alphanumeric characters to ensure that any file
     * path (including absolute OS paths and arbitrary identifiers) maps to a valid,
     * unique JVM class name.
     *
     * @param filePath The file path.
     * @return The JVM internal class name (slash-separated packages).
     */
    private fun filePathToClassName(filePath: String): String {
        val sanitized = buildString {
            for (char in filePath) {
                when {
                    char.isLetterOrDigit() -> append(char)
                    else -> append("_${char.code.toString(16).uppercase().padStart(2, '0')}")
                }
            }
        }
        return "com/mdeo/script/generated/Script_$sanitized"
    }

    /**
     * Compiles a single file to bytecode.
     *
     * @param filePath The file path (used as the JVM source-file debug attribute).
     * @param ast The [TypedAst] for the file.
     * @param className The JVM internal class name.
     * @param generatedInterfaces Shared map for collecting generated functional interfaces.
     * @param functionRegistry The function registry for resolving file-scope and imported
     *   functions.
     * @param typeRegistry The type registry for type lookups (including metamodel types).
     * @param fileScopePropertyRegistry Registry for file-scope (level 1) identifiers such as
     *   class/enum containers.
     * @return The compiled bytecode.
     */
    private fun compileFile(
        filePath: String,
        ast: TypedAst,
        className: String,
        generatedInterfaces: MutableMap<String, ByteArray>,
        functionRegistry: FunctionRegistry,
        typeRegistry: TypeRegistry = TypeRegistry.GLOBAL,
        fileScopePropertyRegistry: GlobalPropertyRegistry = GlobalPropertyRegistry()
    ): ByteArray {
        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)

        cw.visit(
            Opcodes.V11,
            Opcodes.ACC_PUBLIC,
            className,
            null,
            "java/lang/Object",
            null
        )

        cw.visitSource(filePath, null)

        for (function in ast.functions) {
            compileFunction(
                function, ast, className, cw, generatedInterfaces,
                functionRegistry, typeRegistry, fileScopePropertyRegistry
            )
        }

        cw.visitEnd()

        return cw.toByteArray()
    }

    /**
     * Compiles a function to a static method.
     *
     * @param function The function to compile.
     * @param ast The [TypedAst] containing type information.
     * @param className The JVM internal class name.
     * @param cw The [ClassWriter] to emit bytecode to.
     * @param generatedInterfaces Shared map for collecting generated functional interfaces.
     * @param functionRegistry The function registry for resolving function references.
     * @param typeRegistry The type registry for type lookups.
     * @param fileScopePropertyRegistry Registry for file-scope (level 1) identifiers such as
     *   class/enum containers.
     */
    private fun compileFunction(
        function: TypedFunction,
        ast: TypedAst,
        className: String,
        cw: ClassWriter,
        generatedInterfaces: MutableMap<String, ByteArray>,
        functionRegistry: FunctionRegistry,
        typeRegistry: TypeRegistry = TypeRegistry.GLOBAL,
        fileScopePropertyRegistry: GlobalPropertyRegistry = GlobalPropertyRegistry()
    ) {
        val returnType = ast.types[function.returnType]
        val descriptor = functionRegistry.lookupFunction(function.name)!!.getOverload("")!!.descriptor

        val mv = cw.visitMethod(
            Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC,
            function.name,
            descriptor,
            null,
            null
        )

        val paramsScope = Scope(level = 2)

        for (param in function.parameters) {
            val paramType = ast.types[param.type]
            paramsScope.declareVariable(param.name, paramType)
        }

        val tempContext = CompilationContext(
            ast, className, expressionCompilers, statementCompilers, function.returnType,
            paramsScope, classWriter = cw, generatedInterfaces = generatedInterfaces,
            functionRegistry = functionRegistry, typeRegistry = typeRegistry,
            fileScopePropertyRegistry = fileScopePropertyRegistry
        )

        val scopeBuilder = ScopeBuilder(tempContext)
        val bodyScope = scopeBuilder.buildFunctionScope(function, paramsScope)

        val indexAssigner = LocalVariableIndexAssigner(tempContext)
        indexAssigner.assignIndices(paramsScope, isStatic = true)

        val context = CompilationContext(
            ast, className, expressionCompilers, statementCompilers, function.returnType,
            paramsScope, scopeBuilder.statementScopes, classWriter = cw,
            generatedInterfaces = generatedInterfaces, functionRegistry = functionRegistry,
            typeRegistry = typeRegistry, fileScopePropertyRegistry = fileScopePropertyRegistry
        )
        context.enterScope(bodyScope)

        mv.visitCode()

        for (statement in function.body.body) {
            context.compileStatement(statement, mv)
        }

        ensureReturn(returnType, mv)

        mv.visitMaxs(0, 0)
        mv.visitEnd()
    }

    /**
     * Ensures the method ends with a return instruction.
     *
     * Adds a void return at the end of the method regardless of whether the body already
     * terminates with a return.  This is safe because ASM's control-flow analysis drops
     * unreachable instructions.
     *
     * @param returnType The declared return type of the method.
     * @param mv The method visitor.
     */
    private fun ensureReturn(returnType: ReturnType, mv: MethodVisitor) {
        if (returnType is VoidType) {
            mv.visitInsn(Opcodes.RETURN)
        }
    }
}

/**
 * Bundles the two registries produced from metamodel data so they can be passed
 * around as a single value.
 */
private data class TypeRegistries(
    val typeRegistry: TypeRegistry,
    val fileScopePropertyRegistry: GlobalPropertyRegistry
)