package com.mdeo.metamodel

/**
 * Runtime helper with static methods that generated bytecode calls to
 * extract or manipulate values in Set-backed property fields based on multiplicity.
 */
object MultiplicityAccessHelper {

    /**
     * Extracts the first element from a Set, or returns null if the Set is empty.
     *
     * Used by generated `getPropertyByKey` bytecode for single-multiplicity fields.
     * No multiplicity validation is performed.
     *
     * @param set The backing Set to extract from.
     * @return The first element, or null if empty.
     */
    @JvmStatic
    fun extractFirst(set: Set<*>): Any? = set.firstOrNull()

    /**
     * Extracts the single value from a [1..1] (required, single-valued) property.
     *
     * @param set The backing Set.
     * @return The single element.
     * @throws IllegalStateException if the Set is empty or contains more than one element.
     */
    @JvmStatic
    fun extractSingleRequired(set: Set<*>): Any? {
        if (set.isEmpty()) throw IllegalStateException("Required [1..1] property has no value")
        if (set.size > 1) throw IllegalStateException("[1..1] property has ${set.size} values, expected exactly 1")
        return set.first()
    }

    /**
     * Extracts the single value from a [0..1] (optional, single-valued) property.
     *
     * @param set The backing Set.
     * @return The single element, or null if the Set is empty.
     * @throws IllegalStateException if the Set contains more than one element.
     */
    @JvmStatic
    fun extractSingleOptional(set: Set<*>): Any? {
        if (set.size > 1) throw IllegalStateException("[0..1] property has ${set.size} values, expected at most 1")
        return set.firstOrNull()
    }

    /**
     * Replaces the content of a single-valued property's backing Set.
     *
     * Clears the Set first, then adds the value if non-null.
     * Used by generated `setPropertyByKey` bytecode for single-multiplicity fields.
     *
     * @param set The backing Set to modify.
     * @param value The new value, or null to clear.
     */
    @JvmStatic
    @Suppress("UNCHECKED_CAST")
    fun setSingle(set: MutableSet<Any?>, value: Any?) {
        set.clear()
        if (value != null) set.add(value)
    }
}
