package com.mdeo.script.compiler.expressions

import com.mdeo.script.ast.expressions.TypedBinaryExpression
import com.mdeo.script.compiler.CompilationContext
import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Helper for compiling logical binary operations.
 * 
 * Handles the following boolean operators:
 * - Logical AND (&&)
 * - Logical OR (||)
 * 
 * Both operators use short-circuit evaluation:
 * - For &&: if left is false, right is not evaluated
 * - For ||: if left is true, right is not evaluated
 * 
 * The operands must be boolean types. The result is always a boolean
 * (int 0 or 1 on the JVM stack).
 */
object LogicalOperationHelper {

    /**
     * Compiles logical AND (&&) with short-circuit evaluation.
     *
     * If the left operand evaluates to false, the right operand is skipped
     * and the result is false. Otherwise, the result is the value of the
     * right operand.
     *
     * Generated bytecode structure:
     * ```
     *   [evaluate left]
     *   IFEQ falseLabel      ; if left is false, skip to false
     *   [evaluate right]
     *   IFEQ falseLabel      ; if right is false, go to false
     *   ICONST_1             ; result is true
     *   GOTO endLabel
     * falseLabel:
     *   ICONST_0             ; result is false
     * endLabel:
     * ```
     *
     * @param expr The binary expression AST node
     * @param context The compilation context
     * @param mv The ASM method visitor
     * @return Unit. The compiled bytecode leaves a boolean (0 or 1) on the JVM stack.
     */
    fun compileLogicalAnd(
        expr: TypedBinaryExpression,
        context: CompilationContext,
        mv: MethodVisitor
    ) {
        val falseLabel = Label()
        val endLabel = Label()

        context.compileExpression(expr.left, mv)
        mv.visitJumpInsn(Opcodes.IFEQ, falseLabel)

        context.compileExpression(expr.right, mv)
        mv.visitJumpInsn(Opcodes.IFEQ, falseLabel)

        mv.visitInsn(Opcodes.ICONST_1)
        mv.visitJumpInsn(Opcodes.GOTO, endLabel)

        mv.visitLabel(falseLabel)
        mv.visitInsn(Opcodes.ICONST_0)

        mv.visitLabel(endLabel)
    }

    /**
     * Compiles logical OR (||) with short-circuit evaluation.
     *
     * If the left operand evaluates to true, the right operand is skipped
     * and the result is true. Otherwise, the result is the value of the
     * right operand.
     *
     * Generated bytecode structure:
     * ```
     *   [evaluate left]
     *   IFNE trueLabel       ; if left is true, skip to true
     *   [evaluate right]
     *   IFNE trueLabel       ; if right is true, go to true
     *   ICONST_0             ; result is false
     *   GOTO endLabel
     * trueLabel:
     *   ICONST_1             ; result is true
     * endLabel:
     * ```
     *
     * @param expr The binary expression AST node
     * @param context The compilation context
     * @param mv The ASM method visitor
     * @return Unit. The compiled bytecode leaves a boolean (0 or 1) on the JVM stack.
     */
    fun compileLogicalOr(
        expr: TypedBinaryExpression,
        context: CompilationContext,
        mv: MethodVisitor
    ) {
        val trueLabel = Label()
        val endLabel = Label()

        context.compileExpression(expr.left, mv)
        mv.visitJumpInsn(Opcodes.IFNE, trueLabel)

        context.compileExpression(expr.right, mv)
        mv.visitJumpInsn(Opcodes.IFNE, trueLabel)

        mv.visitInsn(Opcodes.ICONST_0)
        mv.visitJumpInsn(Opcodes.GOTO, endLabel)

        mv.visitLabel(trueLabel)
        mv.visitInsn(Opcodes.ICONST_1)

        mv.visitLabel(endLabel)
    }
}
