package com.mdeo.script.compiler.expressions

import com.mdeo.expression.ast.expressions.TypedBinaryExpression
import com.mdeo.expression.ast.types.ClassTypeRef
import com.mdeo.script.compiler.CompilationContext
import com.mdeo.script.compiler.util.CoercionUtil
import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Helper for compiling the null coalescing operator (??).
 *
 * The null coalescing operator evaluates the left operand, and if it is null,
 * evaluates and returns the right operand. This follows JavaScript/Kotlin semantics.
 *
 * Example:
 * ```
 * val x: int? = null
 * val y = x ?? 42  // y = 42
 * 
 * val a: int? = 10
 * val b = a ?? 42  // b = 10
 * ```
 *
 * Short-circuit evaluation: the right operand is only evaluated if the left is null.
 */
object NullCoalescingHelper {

    /**
     * Compiles a null coalescing expression (??) to bytecode.
     *
     * The result type is the evalType of the binary expression.
     * Both paths (null and non-null) leave a value of this type on the stack.
     *
     * Generated bytecode structure:
     * ```
     *   [evaluate left as its natural type (nullable)]
     *   DUP
     *   IFNONNULL notNullLabel  ; if left is not null, skip right
     *   POP                      ; discard null
     *   [evaluate right as result type]
     *   GOTO endLabel
     * notNullLabel:
     *   [coerce left to result type if needed]
     * endLabel:
     * ```
     *
     * @param expr The binary expression AST node.
     * @param context The compilation context.
     * @param mv The ASM method visitor.
     */
    fun compileNullCoalescing(
        expr: TypedBinaryExpression,
        context: CompilationContext,
        mv: MethodVisitor
    ) {
        val notNullLabel = Label()
        val endLabel = Label()
        
        val resultType = context.getType(expr.evalType)
        val leftType = context.getType(expr.left.evalType)

        context.compileExpression(expr.left, mv, leftType)
        
        mv.visitInsn(Opcodes.DUP)
        mv.visitJumpInsn(Opcodes.IFNONNULL, notNullLabel)
        
        mv.visitInsn(Opcodes.POP)
        
        context.compileExpression(expr.right, mv, resultType)
        
        mv.visitJumpInsn(Opcodes.GOTO, endLabel)
        
        mv.visitLabel(notNullLabel)
        
        CoercionUtil.emitCoercion(leftType, resultType, mv, context)
        
        mv.visitLabel(endLabel)
    }
}
